import type { Kysely } from "kysely"
import { Database } from "../types/index.js"

export async function up(db: Kysely<Database>): Promise<void> {
  await db.schema
    .alterTable("ws_asset_inventories")
    .dropColumn("asset_model_name")
    .dropColumn("net_capacity")
    .dropColumn("gross_capacity")
    .dropColumn("asset_type_name")
    .dropColumn("min_temperature")
    .dropColumn("max_temperature")
    .dropColumn("manufacture_name")
    .dropColumn("asset_working_status_name")
    .dropColumn("entity_name")
    .dropColumn("borrowed_from_entity_name")
    .dropColumn("budget_source_name")
    .dropColumn("asset_electricity_name")
    .dropColumn("warranty_asset_vendor_name")
    .dropColumn("calibration_schedule_name")
    .dropColumn("calibration_asset_vendor_name")
    .dropColumn("maintenance_schedule_name")
    .dropColumn("maintenance_asset_vendor_name")
    .addColumn("contact_person_user_1_number", "varchar(20)", (col) =>
      col.notNull()
    )
    .addColumn("contact_person_user_2_number", "varchar(20)")
    .addColumn("contact_person_user_3_number", "varchar(20)")
    .addColumn("ownership_qty", "integer", (col) => col.notNull())
    .addColumn("other_asset_model_name", "varchar(255)")
    .addColumn("other_net_capacity", "double precision")
    .addColumn("other_gross_capacity", "double precision")
    .addColumn("other_asset_type_name", "varchar(255)")
    .addColumn("other_min_temperature", "double precision")
    .addColumn("other_max_temperature", "double precision")
    .addColumn("other_manufacture_name", "varchar(255)")
    .execute()
}

export async function down(db: Kysely<Database>): Promise<void> {
  await db.schema
    .alterTable("ws_asset_inventories")
    .addColumn("asset_model_name", "varchar(255)", (col) => col.notNull())
    .addColumn("net_capacity", "double precision")
    .addColumn("gross_capacity", "double precision")
    .addColumn("asset_type_name", "varchar(255)", (col) => col.notNull())
    .addColumn("min_temperature", "double precision")
    .addColumn("max_temperature", "double precision")
    .addColumn("manufacture_name", "varchar(255)", (col) => col.notNull())
    .addColumn("asset_working_status_name", "varchar(255)", (col) =>
      col.notNull()
    )
    .addColumn("entity_name", "varchar(255)", (col) => col.notNull())
    .addColumn("borrowed_from_entity_name", "varchar(255)")
    .addColumn("budget_source_name", "varchar(255)", (col) => col.notNull())
    .addColumn("asset_electricity_name", "varchar(255)")
    .addColumn("warranty_asset_vendor_name", "varchar(255)")
    .addColumn("calibration_schedule_name", "varchar(255)")
    .addColumn("calibration_asset_vendor_name", "varchar(255)")
    .addColumn("maintenance_schedule_name", "varchar(255)")
    .addColumn("maintenance_asset_vendor_name", "varchar(255)")
    .dropColumn("contact_person_user_1_number")
    .dropColumn("contact_person_user_2_number")
    .dropColumn("contact_person_user_3_number")
    .dropColumn("ownership_qty")
    .dropColumn("other_asset_model_name")
    .dropColumn("other_net_capacity")
    .dropColumn("other_gross_capacity")
    .dropColumn("other_asset_type_name")
    .dropColumn("other_min_temperature")
    .dropColumn("other_max_temperature")
    .dropColumn("other_manufacture_name")
    .execute()
}
