import { sql, type Kysely } from "kysely"
import { Database } from "../types/index.js"

export async function up(db: Kysely<Database>): Promise<void> {
  const protocols = [
    {
      id: 1,
      name: "Rabies",
      status: 1,
      is_kipi: 0,
      is_medical_history: 0,
      is_identity_type: 1,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 2,
      name: "Dengue",
      status: 1,
      is_kipi: 1,
      is_medical_history: 1,
      is_identity_type: 0,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ]

  const vaccine_methods = [
    {
      id: 1,
      title: "vaccine_method.intra_muscular",
      created_at: new Date(),
      updated_at: new Date(),
      is_multi_patient: 0,
    },
    {
      id: 2,
      title: "vaccine_method.intra_dermal",
      created_at: new Date(),
      updated_at: new Date(),
      is_multi_patient: 1,
    },
  ]

  const vaccine_types = [
    {
      id: 1,
      title: "vaccine_type.pre_exposure",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 2,
      title: "vaccine_type.post_exposure",
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 3,
      title: "vaccine_type.booster",
      created_at: new Date(),
      updated_at: new Date(),
    },
  ]

  const vaccine_sequences = [
    {
      id: 1,
      title: "vaccine_sequence.prep_day_0",
      protocol_id: 1,
      type_id: 1,
      method_id: 1,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 1,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 1,
      next_duration: 3
    },
    {
      id: 2,
      title: "vaccine_sequence.prep_day_7",
      protocol_id: 1,
      type_id: 1,
      method_id: 1,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 2,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: 7
    },
    {
      id: 3,
      title: "vaccine_sequence.pep_day_0",
      protocol_id: 1,
      type_id: 2,
      method_id: 1,
      min: 1,
      max: 2,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 3,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 1,
      next_duration: 3
    },
    {
      id: 4,
      title: "vaccine_sequence.pep_day_7",
      protocol_id: 1,
      type_id: 2,
      method_id: 1,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 5,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null
    },
    {
      id: 5,
      title: "vaccine_sequence.pep_day_21-28",
      protocol_id: 1,
      type_id: 2,
      method_id: 1,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 7,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null
    },
    {
      id: 6,
      title: "vaccine_sequence.booster_day_0",
      protocol_id: 1,
      type_id: 3,
      method_id: 1,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 8,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null
    },
    {
      id: 7,
      title: "vaccine_sequence.booster_day_3",
      protocol_id: 1,
      type_id: 3,
      method_id: 1,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 9,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null
    },
    {
      id: 8,
      title: "vaccine_sequence.prep_day_0",
      protocol_id: 1,
      type_id: 1,
      method_id: 2,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: -1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 1,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 1,
      next_duration: null
    },
    {
      id: 9,
      title: "vaccine_sequence.prep_day_7",
      protocol_id: 1,
      type_id: 1,
      method_id: 2,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 2,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null
    },
    {
      id: 10,
      title: "vaccine_sequence.pep_day_0",
      protocol_id: 1,
      type_id: 2,
      method_id: 2,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 3,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 1,
      next_duration: null
    },
    {
      id: 11,
      title: "vaccine_sequence.pep_day_3",
      protocol_id: 1,
      type_id: 2,
      method_id: 2,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 4,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null
    },
    {
      id: 12,
      title: "vaccine_sequence.pep_day_7",
      protocol_id: 1,
      type_id: 2,
      method_id: 2,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 5,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null
    },
    {
      id: 13,
      title: "vaccine_sequence.booster_day_0",
      protocol_id: 1,
      type_id: 3,
      method_id: 2,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 8,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null
    },
    {
      id: 14,
      title: "vaccine_sequence.booster_day_3",
      protocol_id: 1,
      type_id: 3,
      method_id: 2,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 9,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null
    },
    {
      id: 15,
      title: "vaccine_sequence.pep_day_3",
      protocol_id: 1,
      type_id: 2,
      method_id: 1,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 4,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null
    },
    {
      id: 16,
      title: "vaccine_sequence.pep_day_14",
      protocol_id: 1,
      type_id: 2,
      method_id: 1,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 6,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null
    },
    {
      id: 19,
      title: "vaccine_sequence.dose_1",
      protocol_id: 2,
      type_id: null,
      method_id: null,
      min: null,
      max: null,
      active_duration: 1,
      start_notification: null,
      end_notification: null,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 1,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 1,
      next_duration: null
    },
    {
      id: 20,
      title: "vaccine_sequence.dose_2",
      protocol_id: 2,
      type_id: null,
      method_id: null,
      min: null,
      max: null,
      active_duration: 1,
      start_notification: null,
      end_notification: null,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 2,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 1,
      next_duration: null
    },
  ]

  const vaccine_rules = [
    {
      protocol_id: 1,
      previous_sequence: 8,
      next_sequence: 9,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 3,
      next_sequence: 15,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: 1,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 8,
      next_sequence: 10,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: 1,
      prerequisite_age: 10,
      prerequisite_interval: 10,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 15,
      next_sequence: 4,
      before_sequence: 3,
      other_sequences: null,
      prerequisite_qty: 1,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 4,
      next_sequence: 16,
      before_sequence: 15,
      other_sequences: null,
      prerequisite_qty: 1,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 3,
      next_sequence: 4,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: 2,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 4,
      next_sequence: 5,
      before_sequence: 3,
      other_sequences: null,
      prerequisite_qty: 1,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 16,
      next_sequence: 6,
      before_sequence: 4,
      other_sequences: null,
      prerequisite_qty: 1,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 5,
      next_sequence: 6,
      before_sequence: 4,
      other_sequences: null,
      prerequisite_qty: 1,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 6,
      next_sequence: 7,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: 1,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 1,
      next_sequence: 2,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: 1,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 1,
      next_sequence: 3,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: 1,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 2,
      next_sequence: 3,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: 0,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: null,
      next_sequence: 2,
      before_sequence: null,
      other_sequences: "[1]",
      prerequisite_qty: 1,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: null,
      next_sequence: 3,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: null,
      next_sequence: 15,
      before_sequence: null,
      other_sequences: "[3]",
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: null,
      next_sequence: 4,
      before_sequence: null,
      other_sequences: "[3,15]",
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: null,
      next_sequence: 16,
      before_sequence: null,
      other_sequences: "[3,15,4]",
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: null,
      next_sequence: 5,
      before_sequence: null,
      other_sequences: "[3,4]",
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: null,
      next_sequence: 1,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 10,
      next_sequence: 11,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: 1,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 11,
      next_sequence: 12,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: 1,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 12,
      next_sequence: 13,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: 1,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 13,
      next_sequence: 14,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: null,
      next_sequence: 10,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: 1,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: null,
      next_sequence: 11,
      before_sequence: null,
      other_sequences: "[10]",
      prerequisite_qty: 1,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: null,
      next_sequence: 12,
      before_sequence: null,
      other_sequences: "[10,11]",
      prerequisite_qty: 1,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: null,
      next_sequence: 8,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: null,
      next_sequence: 9,
      before_sequence: null,
      other_sequences: "[8]",
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 2,
      previous_sequence: null,
      next_sequence: 19,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 2,
      previous_sequence: 19,
      next_sequence: 20,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 2,
      previous_sequence: null,
      next_sequence: 20,
      before_sequence: null,
      other_sequences: "[19]",
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 3,
      next_sequence: 6,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: 2,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 4,
      next_sequence: 6,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: null,
      next_sequence: null,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 2,
      next_sequence: 6,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: 1,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: null,
      next_sequence: 6,
      before_sequence: null,
      other_sequences: "[1,2,3,15,4,16,5]",
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 2,
      previous_sequence: 20,
      next_sequence: 19,
      before_sequence: 19,
      other_sequences: null,
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 2,
      previous_sequence: 20,
      next_sequence: 20,
      before_sequence: 19,
      other_sequences: "[19]",
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 2,
      previous_sequence: 19,
      next_sequence: 20,
      before_sequence: 20,
      other_sequences: null,
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 2,
      previous_sequence: 19,
      next_sequence: 19,
      before_sequence: 20,
      other_sequences: "[20]",
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 2,
      previous_sequence: 19,
      next_sequence: 19,
      before_sequence: 19,
      other_sequences: "[20]",
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 1,
      next_sequence: 6,
      before_sequence: null,
      other_sequences: "[2]",
      prerequisite_qty: 1,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 8,
      next_sequence: 13,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
    {
      protocol_id: 1,
      previous_sequence: 9,
      next_sequence: 13,
      before_sequence: null,
      other_sequences: null,
      prerequisite_qty: null,
      prerequisite_age: null,
      prerequisite_interval: null,
      deleted_at: null,
    },
  ]

  await db
    .insertInto("protocols")
    .values(protocols)
    .onDuplicateKeyUpdate({
      name: sql`values(name)`,
      updated_at: sql`values(updated_at)`,
    })
    .execute()

  await db
    .insertInto("vaccine_methods")
    .values(vaccine_methods)
    .onDuplicateKeyUpdate({
      title: sql`values(title)`,
      is_multi_patient: sql`values(is_multi_patient)`,
      updated_at: sql`values(updated_at)`,
    })
    .execute()

  await db
    .insertInto("vaccine_types")
    .values(vaccine_types)
    .onDuplicateKeyUpdate({
      title: sql`values(title)`,
      updated_at: sql`values(updated_at)`,
    }).execute()

  await db
    .insertInto("ws_vaccine_sequences")
    .values(vaccine_sequences)
    .onDuplicateKeyUpdate({
      title: sql`values(title)`,
      protocol_id: sql`values(protocol_id)`,
      type_id: sql`values(type_id)`,
      method_id: sql`values(method_id)`,
      min: sql`values(min)`,
      max: sql`values(max)`,
      active_duration: sql`values(active_duration)`,
      start_notification: sql`values(start_notification)`,
      end_notification: sql`values(end_notification)`,
      restrict_duration: sql`values(restrict_duration)`,
      max_age: sql`values(max_age)`,
      ideal_age: sql`values(ideal_age)`,
      sort: sql`values(sort)`,
      updated_at: sql`values(updated_at)`,
      is_start_sequence: sql`values(is_start_sequence)`,
      next_duration: sql`values(next_duration)`,
    }).execute()

  await sql`TRUNCATE TABLE ws_vaccine_rules`.execute(db)

  await db.insertInto("ws_vaccine_rules").values(vaccine_rules).execute()
}

export async function down(db: Kysely<Database>): Promise<void> {
  await sql`TRUNCATE TABLE ws_vaccine_rules`.execute(db)
}
