import { sql, type Kysely } from "kysely"
import { Database } from "../types/index.js"

export async function up(db: Kysely<Database>): Promise<void> {
  await db.schema
    .alterTable("ws_vaccine_sequences")
    .addColumn("day_start", "smallint")
    .addColumn("day_end", "smallint")
    .execute()

  const vaccine_sequences = [
    {
      id: 1,
      title: "vaccine_sequence.prep_day_0",
      protocol_id: 1,
      type_id: 1,
      method_id: 1,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 1,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 1,
      next_duration: 3,
      day_start: 0,
      day_end: 0,
    },
    {
      id: 2,
      title: "vaccine_sequence.prep_day_7",
      protocol_id: 1,
      type_id: 1,
      method_id: 1,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 2,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: 7,
      day_start: 7,
      day_end: 7,
    },
    {
      id: 3,
      title: "vaccine_sequence.pep_day_0",
      protocol_id: 1,
      type_id: 2,
      method_id: 1,
      min: 1,
      max: 2,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 3,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 1,
      next_duration: 3,
      day_start: 0,
      day_end: 0,
    },
    {
      id: 4,
      title: "vaccine_sequence.pep_day_7",
      protocol_id: 1,
      type_id: 2,
      method_id: 1,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 5,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null,
      day_start: 7,
      day_end: 7,
    },
    {
      id: 5,
      title: "vaccine_sequence.pep_day_21-28",
      protocol_id: 1,
      type_id: 2,
      method_id: 1,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 7,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null,
      day_start: 21,
      day_end: 28,
    },
    {
      id: 6,
      title: "vaccine_sequence.booster_day_0",
      protocol_id: 1,
      type_id: 3,
      method_id: 1,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 8,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null,
      day_start: 0,
      day_end: 0,
    },
    {
      id: 7,
      title: "vaccine_sequence.booster_day_3",
      protocol_id: 1,
      type_id: 3,
      method_id: 1,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 9,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null,
      day_start: 3,
      day_end: 3,
    },
    {
      id: 8,
      title: "vaccine_sequence.prep_day_0",
      protocol_id: 1,
      type_id: 1,
      method_id: 2,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: -1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 1,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 1,
      next_duration: null,
      day_start: 0,
      day_end: 0,
    },
    {
      id: 9,
      title: "vaccine_sequence.prep_day_7",
      protocol_id: 1,
      type_id: 1,
      method_id: 2,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 2,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null,
      day_start: 7,
      day_end: 7,
    },
    {
      id: 10,
      title: "vaccine_sequence.pep_day_0",
      protocol_id: 1,
      type_id: 2,
      method_id: 2,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 3,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 1,
      next_duration: null,
      day_start: 0,
      day_end: 0,
    },
    {
      id: 11,
      title: "vaccine_sequence.pep_day_3",
      protocol_id: 1,
      type_id: 2,
      method_id: 2,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 4,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null,
      day_start: 3,
      day_end: 3,
    },
    {
      id: 12,
      title: "vaccine_sequence.pep_day_7",
      protocol_id: 1,
      type_id: 2,
      method_id: 2,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 5,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null,
      day_start: 7,
      day_end: 7,
    },
    {
      id: 13,
      title: "vaccine_sequence.booster_day_0",
      protocol_id: 1,
      type_id: 3,
      method_id: 2,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 8,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null,
      day_start: 0,
      day_end: 0,
    },
    {
      id: 14,
      title: "vaccine_sequence.booster_day_3",
      protocol_id: 1,
      type_id: 3,
      method_id: 2,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 9,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null,
      day_start: 3,
      day_end: 3,
    },
    {
      id: 15,
      title: "vaccine_sequence.pep_day_3",
      protocol_id: 1,
      type_id: 2,
      method_id: 1,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 4,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null,
      day_start: 3,
      day_end: 3,
    },
    {
      id: 16,
      title: "vaccine_sequence.pep_day_14",
      protocol_id: 1,
      type_id: 2,
      method_id: 1,
      min: 1,
      max: 1,
      active_duration: 365,
      start_notification: 1,
      end_notification: 14,
      restrict_duration: null,
      max_age: null,
      ideal_age: null,
      sort: 6,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      is_start_sequence: 0,
      next_duration: null,
      day_start: 14,
      day_end: 14,
    }
  ]

  await db
      .insertInto("ws_vaccine_sequences")
      .values(vaccine_sequences)
      .onDuplicateKeyUpdate({
        title: sql`values(title)`,
        protocol_id: sql`values(protocol_id)`,
        type_id: sql`values(type_id)`,
        method_id: sql`values(method_id)`,
        min: sql`values(min)`,
        max: sql`values(max)`,
        active_duration: sql`values(active_duration)`,
        start_notification: sql`values(start_notification)`,
        end_notification: sql`values(end_notification)`,
        restrict_duration: sql`values(restrict_duration)`,
        max_age: sql`values(max_age)`,
        ideal_age: sql`values(ideal_age)`,
        sort: sql`values(sort)`,
        updated_at: sql`values(updated_at)`,
        is_start_sequence: sql`values(is_start_sequence)`,
        next_duration: sql`values(next_duration)`,
        day_start: sql`values(day_start)`,
        day_end: sql`values(day_end)`
      }).execute()
}

export async function down(db: Kysely<Database>): Promise<void> {
  await db.schema
    .alterTable("ws_vaccine_sequences")
    .dropColumn("day_start")
    .dropColumn("day_end")
    .execute()
}
