import { Database } from "@smile/lib/types/database/mod.js"
import { Kysely, sql } from "kysely"

export async function up(db: Kysely<Database>): Promise<void> {
  // Truncate all environmental tables before seeding (child tables first)
  await sql`SET FOREIGN_KEY_CHECKS = 0`.execute(db)
  await sql`TRUNCATE TABLE ws_activity_environmental_parameter_categories`.execute(db)
  await sql`TRUNCATE TABLE ws_environmental_parameter_category_details`.execute(db)
  await sql`TRUNCATE TABLE environmental_parameter_options`.execute(db)
  await sql`TRUNCATE TABLE environmental_parameter_validation_rules`.execute(db)
  await sql`TRUNCATE TABLE environmental_parameter_categories_fields`.execute(db)
  await sql`TRUNCATE TABLE environmental_test_methods`.execute(db)
  await sql`TRUNCATE TABLE environmental_analysis_parameters`.execute(db)
  await sql`TRUNCATE TABLE environmental_parameter_categories`.execute(db)
  await sql`TRUNCATE TABLE environmental_units`.execute(db)
  await sql`SET FOREIGN_KEY_CHECKS = 1`.execute(db)

  // Seeding table: environmental_units
  await db.transaction().execute(async (trx) => {
    await trx
      .insertInto("environmental_units" as any)
      .values([
        {
          id: 1,
          name: "°C",
        },
        {
          id: 2,
          name: "mg/L",
        },
        {
          id: 3,
          name: "NTU",
        },
        {
          id: 4,
          name: "TCU",
        },
        {
          id: 5,
          name: "-",
        },
        {
          id: 6,
          name: "satuan",
        },
        {
          id: 7,
          name: "CFU/m3",
        },
        {
          id: 8,
          name: "CFU/100 mL",
        },
        {
          id: 9,
          name: "CFU/g",
        },
        {
          id: 10,
          name: "mg/25g",
        },
        {
          id: 11,
          name: "/25g",
        },
        {
          id: 12,
          name: "MPN/g",
        },
      ])
      .execute()
  })

  // Seeding table: environmental_parameter_categories
  await db.transaction().execute(async (trx) => {
    await trx
      .insertInto("environmental_parameter_categories" as any)
      .values([
        {
          id: 1,
          name: "Pemeriksaan Mikrobiologi",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 2,
          name: "Pengujian Air minum",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 3,
          name: "Mikrobiologi Air Minum Total Coliform dan E.Coli",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 4,
          name: "Analisis BTP",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 5,
          name: "Makanan - SLS",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 6,
          name: "Usap Alat - SLS",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 7,
          name: "Mikrobiologi Lingkungan",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 8,
          name: "Pengujian Makanan/Minuman",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 9,
          name: "Pengujian Vektor",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 10,
          name: "Pemeriksaan Udara",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 11,
          name: "Pemeriksaan Zat Besi",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 12,
          name: "Kualitas Air Pakai",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
      ])
      .execute()
  })

  // Seeding table: environmental_analysis_parameters
  await db.transaction().execute(async (trx) => {
    await trx
      .insertInto("environmental_analysis_parameters" as any)
      .values([
        {
          id: 1,
          name: "Bau",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 5,
        },
        {
          id: 2,
          name: "Besi terlarut",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 3,
          name: "Suhu",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 1,
        },
        {
          id: 4,
          name: "Suhu Insitu",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 1,
        },
        {
          id: 5,
          name: "Warna",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 4,
        },
        {
          id: 6,
          name: "Zat Padat Terlarut",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 7,
          name: "Kekeruhan",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 3,
        },
        {
          id: 8,
          name: "pH Insitu",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 5,
        },
        {
          id: 9,
          name: "Nitrat ( N03-N Terlarut )",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 10,
          name: "Nitrat ( N02-N Terlarut )",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 11,
          name: "Kromium Heksavalen ( Cr6+terlarut* )",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 12,
          name: "Besi ( terlarut )",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 13,
          name: "Mangan ( terlarut )",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 14,
          name: "Sisa Khlor Eksitu ( terlarut* )",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 15,
          name: "Arsen ( terlarut )",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 16,
          name: "Kadmium ( terlarut )",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 17,
          name: "Timbal ( terlarut )",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 18,
          name: "Fluorida ( terlarut )",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 19,
          name: "Alumunium ( terlarut )",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 20,
          name: "Total Dissolve Solid (TDS)*",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 21,
          name: "pH*",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 5,
        },
        {
          id: 22,
          name: "Nitrit ( sebagai NO² terlarut )",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 23,
          name: "Nitrat ( sebagai NO³ terlarut )",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 24,
          name: "Kromium valensi 6 (Cr⁶⁺) (terlarut)",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 25,
          name: "Besi (Fe) terlarut",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 26,
          name: "Mangan (Mn)",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 27,
          name: "Sisa khlor terlarut",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 28,
          name: "Arsen (As) terlarut",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 29,
          name: "Kadmium (Cd)",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 30,
          name: "Timbal (Pb)",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 31,
          name: "Fluorida (F) terlarut",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 32,
          name: "Aluminium (Al) terlarut",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 2,
        },
        {
          id: 33,
          name: "Yeast & Molds",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 7,
        },
        {
          id: 34,
          name: "Angka Kuman",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 7,
        },
        {
          id: 35,
          name: "Escherichia coli",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 9,
        },
        {
          id: 36,
          name: "Total Coliform",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 8,
        },
        {
          id: 37,
          name: "pH Lab",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 5,
        },
        {
          id: 38,
          name: "Boraks",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 5,
        },
        {
          id: 39,
          name: "Formalin",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 10,
        },
        {
          id: 40,
          name: "Rhodamine B",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 10,
        },
        {
          id: 41,
          name: "Methanil Yellow",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 11,
        },
        {
          id: 42,
          name: "Salmonella sp",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 11,
        },
        {
          id: 43,
          name: "Staphylococcus Aureus",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 9,
        },
        {
          id: 44,
          name: "Virus Dengue",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 5,
        },
        {
          id: 45,
          name: "Staphylococcus Aureus Methanil Yellow",
          result_data_type: "Free Text",
          created_by: null,
          updated_by: null,
          deleted_by: null,
          unit_id: 1,
        },
      ])
      .execute()
  })

  // Seeding table: environmental_test_methods
  await db.transaction().execute(async (trx) => {
    await trx
      .insertInto("environmental_test_methods" as any)
      .values([
        {
          id: 1,
          name: "APHA 2021B",
          deskripsi: null,
          quality_standard: "10",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 2,
          name: "SNI 3554-2015",
          deskripsi: null,
          quality_standard: "Tidak berbau",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 3,
          name: "SNI 3029-00239",
          deskripsi: "-",
          quality_standard: "50",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 4,
          name: "Photometric",
          deskripsi: "Sisa khlor terlarut",
          quality_standard: "0,2 – 0,5 dengan waktu kontak 30 menit",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 5,
          name: "Turbidimetri",
          deskripsi: null,
          quality_standard: "< 3",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 6,
          name: "IK.03/PP16.5-Air-17025/Labkesda",
          deskripsi: "Suhu Insitu",
          quality_standard: "Suhu Udara ± 3°",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 7,
          name: "IK.01/PP16.5-Air-17025/Labkesda",
          deskripsi: "Zat Padat Terlarut",
          quality_standard: "300",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 8,
          name: "IK.02/PP16.5-Air-17025/Labkesda",
          deskripsi: "Kekeruhan",
          quality_standard: "3",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 9,
          name: "SNI 06-6989.80:2011",
          deskripsi: "Warna",
          quality_standard: "10",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 10,
          name: "SNI 01-3554:2015",
          deskripsi: "Bau",
          quality_standard: "Tidak Berbau",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 11,
          name: "SNI 6989.11:2019",
          deskripsi: "pH Insitu",
          quality_standard: "6,5-8,5",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 12,
          name: "Std Met. APHA 4110C/23/2017",
          deskripsi: "Nitrat ( N03-N terlarut )",
          quality_standard: "20",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 13,
          name: "Std Met. APHA 4110C/23/2017",
          deskripsi: "Nitrat ( N02-N terlarut )",
          quality_standard: "3",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 14,
          name: "Std Met. APHA 3500-Cr B/23/2017",
          deskripsi: "Kromium Heksavalen ( Cr6+terlarut* )",
          quality_standard: "0,01",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 15,
          name: "Std Met. APHA 3120B/23/2017;3030B/23/2017",
          deskripsi: "Besi  ( terlarut )",
          quality_standard: "0,2",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 16,
          name: "Std Met. APHA 3120B/23/2017;3030B/23/2017",
          deskripsi: "Mangan ( terlarut )",
          quality_standard: "0,1",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 17,
          name: "IK.19/PP16.5-Air-17025/Labkesda",
          deskripsi: "Sisa Khlor Eksitu ( terlarut* )",
          quality_standard: "-",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 18,
          name: "Std Met. APHA 3120B/23/2017;3030B/23/2017",
          deskripsi: "Arsen ( terlarut )",
          quality_standard: "0,01",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 19,
          name: "Std Met. APHA 3120B/23/2017;3030B/23/2017",
          deskripsi: "Kadmium ( terlarut )",
          quality_standard: "0,003",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 20,
          name: "SNI 06-6989.29:2005",
          deskripsi: "Fluorida ( terlarut )",
          quality_standard: "1,5",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 21,
          name: "Std Met. APHA 3120B/23/2017;3030B/23/2017",
          deskripsi: "Alumunium ( terlarut )",
          quality_standard: "0,0260",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 22,
          name: "SNI 3554-2015",
          deskripsi: "Nitrat (sebagai NO₃⁻ terlarut)",
          quality_standard: "20",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 23,
          name: "SNI 06-6989.9-2004",
          deskripsi: "Nitrit (sebagai NO₂⁻ terlarut)",
          quality_standard: "3",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 24,
          name: "US-EPA Methode 200.8",
          deskripsi: "Kromium valensi 6 (Cr⁶⁺) (terlarut)",
          quality_standard: "0,01",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 25,
          name: "SNI 3554-2015",
          deskripsi: "Besi (Fe) terlarut",
          quality_standard: "0,2",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 26,
          name: "US-EPA Methode 200.8",
          deskripsi: "Mangan (Mn) terlarut",
          quality_standard: "0,1",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 27,
          name: "SNI 9099 : 2024",
          deskripsi: "Yeast & Molds",
          quality_standard: "1000",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 28,
          name: "SNI 9099 : 2024",
          deskripsi: "Angka Kuman",
          quality_standard: "700",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 29,
          name: "US-EPA Methode 200.8",
          deskripsi: "Kadmium (Cd) terlarut",
          quality_standard: "0,003",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 30,
          name: "Photometric",
          deskripsi: "Timbal (Pb) terlarut",
          quality_standard: "1,5",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 31,
          name: "US-EPA Methode 200.8",
          deskripsi: "Aluminium (Al) terlarut",
          quality_standard: "0,2",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 32,
          name: "ISO 9308-1 : 2014",
          deskripsi: null,
          quality_standard: "0",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 33,
          name: "SNI 3554 : 2015",
          deskripsi: "Total Coliform",
          quality_standard: "0",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 34,
          name: "SNI 7251 : 2012",
          deskripsi: "E. Coli",
          quality_standard: "< 3,6",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 35,
          name: "SNI 2897:2008",
          deskripsi: "Salmonella",
          quality_standard: "Negatif",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 36,
          name: "IK/5.3/Mtd02d.18 (Kualitatif)",
          deskripsi: "Boraks",
          quality_standard: "Negatif/25gr",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 37,
          name: "SNI ISO 16649-2:2016",
          deskripsi: null,
          quality_standard: "< 1,1",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 38,
          name: "SM APHA 23rd Ed. 3125 B, 2017",
          deskripsi: null,
          quality_standard: "0,2",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 39,
          name: "SM APHA 23rd Ed. 3030 B",
          deskripsi: null,
          quality_standard: "0,01",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 40,
          name: "3500-Cr B,2017",
          deskripsi: null,
          quality_standard: "0,01",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 41,
          name: "3125 B, 2017",
          deskripsi: null,
          quality_standard: "0,1",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 42,
          name: "SM APHA 23rd Ed. 3030 B",
          deskripsi: null,
          quality_standard: "0,1",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 43,
          name: "IK/5.3/Mtd11a.05 (Spektrofotometri)",
          deskripsi: null,
          quality_standard: "20",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 44,
          name: "IK/5.3/Mtd12a.05 (Spektrofotometri)",
          deskripsi: null,
          quality_standard: "3",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 45,
          name: "IK/5.3/Mtd13a.10 (Potensiometri)",
          deskripsi: null,
          quality_standard: "6,5-8,5",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 46,
          name: "IK.06/PP.16.7-BTP-17025/Labkesda (Spektrofotometri)",
          deskripsi: null,
          quality_standard: "Negatif/25 g",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 47,
          name: "ISO 6579-1:2017",
          deskripsi: null,
          quality_standard: "Negatif",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 48,
          name: "SNI ISO 7251:2012",
          deskripsi: null,
          quality_standard: "< 3.6",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 49,
          name: "IK.10/PP.16.7-BTP-17025/Labkesda (TLC)",
          deskripsi: null,
          quality_standard: "Negatif/25 g",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 50,
          name: "IK.04/PP.16.7-BTP-17025/Labkesda (Spektrofotometri)",
          deskripsi: null,
          quality_standard: "Negatif/25 g",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 51,
          name: "SNI 6989.27-2019",
          deskripsi: null,
          quality_standard: "< 300",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 52,
          name: "IK. 10/PP.16.7-BTP-17025/Labkesda (TLC)",
          deskripsi: null,
          quality_standard: "Negatif/25 g",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 53,
          name: "SNI 6989.11-2019",
          deskripsi: null,
          quality_standard: "Suhu udara  +/- 3",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 54,
          name: "PP. 16 . 18 - Mikro/17025/LABKESDA",
          deskripsi: null,
          quality_standard: "<1.1",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 55,
          name: "SNI 2897:2008",
          deskripsi: null,
          quality_standard: "< 100",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 56,
          name: "SNI 2894-1992",
          deskripsi: null,
          quality_standard: "Negatif",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 57,
          name: "SNI 01-2895-1992",
          deskripsi: null,
          quality_standard: "Negatif",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 58,
          name: "WHO guideline / ISO 17025",
          deskripsi: null,
          quality_standard: "Positif Negatif",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 59,
          name: "test validate",
          deskripsi: null,
          quality_standard: "a",
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
      ])
      .execute()
  })

  // Seeding table: environmental_parameter_categories_fields
  await db.transaction().execute(async (trx) => {
    await trx
      .insertInto("environmental_parameter_categories_fields" as any)
      .values([
        {
          id: 1,
          environmental_parameter_categories_id: 1,
          key: "jenis_sampel",
          type_data: "text",
          label: "Jenis Sampel",
          hint: "Jenis Sampel",
          mandatory: 0,
          options: null,
        },
        {
          id: 2,
          environmental_parameter_categories_id: 2,
          key: "jenis_bahan_uji",
          type_data: "text",
          label: "Jenis Bahan Uji",
          hint: '"PDAM"',
          mandatory: 0,
          options: null,
        },
        {
          id: 3,
          environmental_parameter_categories_id: 3,
          key: "sample",
          type_data: "text",
          label: "Sample",
          hint: "Sample",
          mandatory: 0,
          options: null,
        },
        {
          id: 4,
          environmental_parameter_categories_id: 10,
          key: "nama_pengujian",
          type_data: "text",
          label: "Nama Pengujian",
          hint: "Masukkan tanggal pengujian",
          mandatory: 1,
          options: null,
        },
        {
          id: 5,
          environmental_parameter_categories_id: 10,
          key: "jumlah_pengujian",
          type_data: "number",
          label: "Jumlah Pengujian",
          hint: "Masukkan jumlah pengujian",
          mandatory: 1,
          options: null,
        },
        {
          id: 6,
          environmental_parameter_categories_id: 10,
          key: "jenis_pengujian",
          type_data: "dropdown",
          label: "Jenis Pengujian",
          hint: "Masukkan jenis pengujian",
          mandatory: 1,
          options: "Uji 1,Uji 2",
        },
        {
          id: 7,
          environmental_parameter_categories_id: 10,
          key: "tanggal_pengujian",
          type_data: "date",
          label: "Tanggal Pengujian",
          hint: "Masukkan tanggal pengujian",
          mandatory: 1,
          options: null,
        },
        {
          id: 8,
          environmental_parameter_categories_id: 12,
          key: "tanggal_sample",
          type_data: "date",
          label: "Tanggal sample",
          hint: "pengambilan",
          mandatory: 1,
          options: null,
        },
      ])
      .execute()
  })

  // Seeding table: environmental_parameter_validation_rules
  await db.transaction().execute(async (trx) => {
    await trx
      .insertInto("environmental_parameter_validation_rules" as any)
      .values([
        {
          id: 1,
          test_method_id: 1,
          result_format_type: "number",
          validation_type: "range",
          min_value: "0.0000",
          max_value: "10.0000",
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 2,
          test_method_id: 2,
          result_format_type: "text",
          validation_type: "options",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 3,
          test_method_id: 3,
          result_format_type: "number",
          validation_type: "range",
          min_value: "10.0000",
          max_value: "50.0000",
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 4,
          test_method_id: 4,
          result_format_type: "number",
          validation_type: "range",
          min_value: "0.0000",
          max_value: "10.0000",
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 1,
        },
        {
          id: 5,
          test_method_id: 5,
          result_format_type: "number",
          validation_type: "comparison",
          min_value: null,
          max_value: null,
          comparison_operator: "<",
          comparison_value: "3.0000",
          allow_decimal: 1,
        },
        {
          id: 6,
          test_method_id: 6,
          result_format_type: "number",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 7,
          test_method_id: 7,
          result_format_type: "number",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 8,
          test_method_id: 8,
          result_format_type: "number",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 9,
          test_method_id: 9,
          result_format_type: "number",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 10,
          test_method_id: 10,
          result_format_type: "text",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 11,
          test_method_id: 11,
          result_format_type: "text",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 12,
          test_method_id: 12,
          result_format_type: "number",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 13,
          test_method_id: 13,
          result_format_type: "text",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 14,
          test_method_id: 14,
          result_format_type: "text",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 15,
          test_method_id: 15,
          result_format_type: "number",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 1,
        },
        {
          id: 16,
          test_method_id: 16,
          result_format_type: "text",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 17,
          test_method_id: 17,
          result_format_type: "number",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 18,
          test_method_id: 18,
          result_format_type: "text",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 19,
          test_method_id: 19,
          result_format_type: "text",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 20,
          test_method_id: 20,
          result_format_type: "text",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 21,
          test_method_id: 21,
          result_format_type: "text",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 22,
          test_method_id: 22,
          result_format_type: "number",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 23,
          test_method_id: 23,
          result_format_type: "number",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 24,
          test_method_id: 24,
          result_format_type: "number",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 1,
        },
        {
          id: 25,
          test_method_id: 25,
          result_format_type: "text",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 26,
          test_method_id: 26,
          result_format_type: "number",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 1,
        },
        {
          id: 27,
          test_method_id: 27,
          result_format_type: "number",
          validation_type: "range",
          min_value: "0.0000",
          max_value: "1000.0000",
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 28,
          test_method_id: 28,
          result_format_type: "number",
          validation_type: "range",
          min_value: "0.0000",
          max_value: "1500.0000",
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 29,
          test_method_id: 29,
          result_format_type: "number",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 1,
        },
        {
          id: 30,
          test_method_id: 30,
          result_format_type: "number",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 1,
        },
        {
          id: 31,
          test_method_id: 31,
          result_format_type: "number",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 1,
        },
        {
          id: 32,
          test_method_id: 32,
          result_format_type: "number",
          validation_type: "range",
          min_value: "0.0000",
          max_value: "1000.0000",
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 1,
        },
        {
          id: 33,
          test_method_id: 33,
          result_format_type: "number",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 34,
          test_method_id: 34,
          result_format_type: "text",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 35,
          test_method_id: 35,
          result_format_type: "number",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 36,
          test_method_id: 36,
          result_format_type: "text",
          validation_type: "options",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 37,
          test_method_id: 37,
          result_format_type: "number",
          validation_type: "range",
          min_value: "0.0000",
          max_value: "10.0000",
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 1,
        },
        {
          id: 38,
          test_method_id: 38,
          result_format_type: "number",
          validation_type: "range",
          min_value: "0.0000",
          max_value: "10.0000",
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 1,
        },
        {
          id: 39,
          test_method_id: 39,
          result_format_type: "number",
          validation_type: "range",
          min_value: "0.0000",
          max_value: "1000.0000",
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 40,
          test_method_id: 40,
          result_format_type: "number",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 1,
        },
        {
          id: 41,
          test_method_id: 41,
          result_format_type: "number",
          validation_type: "range",
          min_value: "0.0000",
          max_value: "10.0000",
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 1,
        },
        {
          id: 42,
          test_method_id: 42,
          result_format_type: "number",
          validation_type: "range",
          min_value: "0.0000",
          max_value: "10.0000",
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 1,
        },
        {
          id: 43,
          test_method_id: 43,
          result_format_type: "number",
          validation_type: "comparison",
          min_value: null,
          max_value: null,
          comparison_operator: "<",
          comparison_value: "100.0000",
          allow_decimal: 1,
        },
        {
          id: 44,
          test_method_id: 44,
          result_format_type: "number",
          validation_type: "comparison",
          min_value: null,
          max_value: null,
          comparison_operator: "<",
          comparison_value: "100.0000",
          allow_decimal: 1,
        },
        {
          id: 45,
          test_method_id: 45,
          result_format_type: "number",
          validation_type: "range",
          min_value: null,
          max_value: "10.0000",
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 1,
        },
        {
          id: 46,
          test_method_id: 46,
          result_format_type: "text",
          validation_type: "options",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 47,
          test_method_id: 47,
          result_format_type: "text",
          validation_type: "options",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 48,
          test_method_id: 48,
          result_format_type: "number",
          validation_type: "range",
          min_value: "0.0000",
          max_value: "10.0000",
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 1,
        },
        {
          id: 49,
          test_method_id: 49,
          result_format_type: "text",
          validation_type: "options",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 50,
          test_method_id: 50,
          result_format_type: "text",
          validation_type: "options",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 51,
          test_method_id: 51,
          result_format_type: "number",
          validation_type: "comparison",
          min_value: null,
          max_value: null,
          comparison_operator: "<",
          comparison_value: "1000.0000",
          allow_decimal: 0,
        },
        {
          id: 52,
          test_method_id: 52,
          result_format_type: "number",
          validation_type: "range",
          min_value: "0.0000",
          max_value: "1000.0000",
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 1,
        },
        {
          id: 53,
          test_method_id: 53,
          result_format_type: "number",
          validation_type: "range",
          min_value: "0.0000",
          max_value: "100.0000",
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 1,
        },
        {
          id: 54,
          test_method_id: 54,
          result_format_type: "number",
          validation_type: "range",
          min_value: "0.0000",
          max_value: "10.0000",
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 1,
        },
        {
          id: 55,
          test_method_id: 55,
          result_format_type: "number",
          validation_type: "comparison",
          min_value: null,
          max_value: null,
          comparison_operator: "<",
          comparison_value: "100.0000",
          allow_decimal: 0,
        },
        {
          id: 56,
          test_method_id: 56,
          result_format_type: "text",
          validation_type: "options",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 57,
          test_method_id: 57,
          result_format_type: "text",
          validation_type: "options",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 58,
          test_method_id: 58,
          result_format_type: "text",
          validation_type: "none",
          min_value: null,
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
        {
          id: 59,
          test_method_id: 59,
          result_format_type: "number",
          validation_type: "range",
          min_value: "1.0000",
          max_value: null,
          comparison_operator: null,
          comparison_value: null,
          allow_decimal: 0,
        },
      ])
      .execute()
  })

  // Seeding table: environmental_parameter_options
  await db.transaction().execute(async (trx) => {
    await trx
      .insertInto("environmental_parameter_options" as any)
      .values([
        {
          id: 1,
          test_method_id: 2,
          option_value: "Berbau",
          sort_order: 0,
        },
        {
          id: 2,
          test_method_id: 2,
          option_value: "Tidak berbau",
          sort_order: 1,
        },
        {
          id: 3,
          test_method_id: 36,
          option_value: "Positif",
          sort_order: 0,
        },
        {
          id: 4,
          test_method_id: 36,
          option_value: "Negatif",
          sort_order: 1,
        },
        {
          id: 5,
          test_method_id: 46,
          option_value: "Negatif",
          sort_order: 0,
        },
        {
          id: 6,
          test_method_id: 46,
          option_value: "Positif",
          sort_order: 1,
        },
        {
          id: 7,
          test_method_id: 47,
          option_value: "Positif",
          sort_order: 0,
        },
        {
          id: 8,
          test_method_id: 47,
          option_value: "Negatif",
          sort_order: 1,
        },
        {
          id: 9,
          test_method_id: 49,
          option_value: "Positif",
          sort_order: 0,
        },
        {
          id: 10,
          test_method_id: 49,
          option_value: "Negatif",
          sort_order: 1,
        },
        {
          id: 11,
          test_method_id: 50,
          option_value: "Positif",
          sort_order: 0,
        },
        {
          id: 12,
          test_method_id: 50,
          option_value: "Negatif",
          sort_order: 1,
        },
        {
          id: 13,
          test_method_id: 56,
          option_value: "Negatif",
          sort_order: 0,
        },
        {
          id: 14,
          test_method_id: 56,
          option_value: "Positif",
          sort_order: 1,
        },
        {
          id: 15,
          test_method_id: 57,
          option_value: "Positif",
          sort_order: 0,
        },
        {
          id: 16,
          test_method_id: 57,
          option_value: "Negatif",
          sort_order: 1,
        },
      ])
      .execute()
  })

  // Seeding table: ws_environmental_parameter_category_details
  await db.transaction().execute(async (trx) => {
    await trx
      .insertInto("ws_environmental_parameter_category_details" as any)
      .values([
        {
          id: 1,
          env_parameter_category_id: 1,
          env_analysis_parameter_id: 33,
          env_test_method_id: 27,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 2,
          env_parameter_category_id: 1,
          env_analysis_parameter_id: 34,
          env_test_method_id: 28,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 3,
          env_parameter_category_id: 4,
          env_analysis_parameter_id: 38,
          env_test_method_id: 50,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 4,
          env_parameter_category_id: 4,
          env_analysis_parameter_id: 39,
          env_test_method_id: 46,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 5,
          env_parameter_category_id: 4,
          env_analysis_parameter_id: 40,
          env_test_method_id: 49,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 6,
          env_parameter_category_id: 4,
          env_analysis_parameter_id: 41,
          env_test_method_id: 52,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 7,
          env_parameter_category_id: 5,
          env_analysis_parameter_id: 42,
          env_test_method_id: 47,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 8,
          env_parameter_category_id: 5,
          env_analysis_parameter_id: 35,
          env_test_method_id: 48,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 9,
          env_parameter_category_id: 6,
          env_analysis_parameter_id: 35,
          env_test_method_id: 54,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 10,
          env_parameter_category_id: 7,
          env_analysis_parameter_id: 43,
          env_test_method_id: 55,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 11,
          env_parameter_category_id: 7,
          env_analysis_parameter_id: 42,
          env_test_method_id: 35,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 12,
          env_parameter_category_id: 7,
          env_analysis_parameter_id: 35,
          env_test_method_id: 48,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 13,
          env_parameter_category_id: 8,
          env_analysis_parameter_id: 38,
          env_test_method_id: 56,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 14,
          env_parameter_category_id: 8,
          env_analysis_parameter_id: 39,
          env_test_method_id: 56,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 15,
          env_parameter_category_id: 8,
          env_analysis_parameter_id: 40,
          env_test_method_id: 57,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 16,
          env_parameter_category_id: 8,
          env_analysis_parameter_id: 41,
          env_test_method_id: 57,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 17,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 4,
          env_test_method_id: 6,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 18,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 1,
          env_test_method_id: 10,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 19,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 3,
          env_test_method_id: 53,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 20,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 5,
          env_test_method_id: 1,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 21,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 5,
          env_test_method_id: 9,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 22,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 6,
          env_test_method_id: 7,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 23,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 7,
          env_test_method_id: 8,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 24,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 7,
          env_test_method_id: 5,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 25,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 8,
          env_test_method_id: 11,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 26,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 9,
          env_test_method_id: 12,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 27,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 9,
          env_test_method_id: 22,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 28,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 11,
          env_test_method_id: 14,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 29,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 12,
          env_test_method_id: 15,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 30,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 13,
          env_test_method_id: 16,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 31,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 13,
          env_test_method_id: 26,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 32,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 14,
          env_test_method_id: 17,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 33,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 14,
          env_test_method_id: 4,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 34,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 15,
          env_test_method_id: 18,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 35,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 15,
          env_test_method_id: 24,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 36,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 16,
          env_test_method_id: 19,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 37,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 16,
          env_test_method_id: 29,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 38,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 17,
          env_test_method_id: 18,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 39,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 17,
          env_test_method_id: 24,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 40,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 18,
          env_test_method_id: 20,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 41,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 18,
          env_test_method_id: 30,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 42,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 19,
          env_test_method_id: 21,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 43,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 19,
          env_test_method_id: 31,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 44,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 22,
          env_test_method_id: 13,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 45,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 22,
          env_test_method_id: 23,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 46,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 21,
          env_test_method_id: 11,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 47,
          env_parameter_category_id: 2,
          env_analysis_parameter_id: 24,
          env_test_method_id: 40,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 48,
          env_parameter_category_id: 3,
          env_analysis_parameter_id: 35,
          env_test_method_id: 32,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 49,
          env_parameter_category_id: 3,
          env_analysis_parameter_id: 35,
          env_test_method_id: 33,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 50,
          env_parameter_category_id: 3,
          env_analysis_parameter_id: 35,
          env_test_method_id: 34,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 51,
          env_parameter_category_id: 3,
          env_analysis_parameter_id: 36,
          env_test_method_id: 32,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 52,
          env_parameter_category_id: 3,
          env_analysis_parameter_id: 36,
          env_test_method_id: 33,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 53,
          env_parameter_category_id: 3,
          env_analysis_parameter_id: 42,
          env_test_method_id: 35,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 54,
          env_parameter_category_id: 3,
          env_analysis_parameter_id: 43,
          env_test_method_id: 55,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 55,
          env_parameter_category_id: 9,
          env_analysis_parameter_id: 44,
          env_test_method_id: 58,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 56,
          env_parameter_category_id: 11,
          env_analysis_parameter_id: 45,
          env_test_method_id: 41,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 57,
          env_parameter_category_id: 10,
          env_analysis_parameter_id: 33,
          env_test_method_id: 27,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 58,
          env_parameter_category_id: 10,
          env_analysis_parameter_id: 34,
          env_test_method_id: 28,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
        {
          id: 59,
          env_parameter_category_id: 12,
          env_analysis_parameter_id: 35,
          env_test_method_id: 41,
          created_by: null,
          updated_by: null,
          deleted_by: null,
        },
      ])
      .execute()
  })

  // Seeding table: ws_activity_environmental_parameter_categories
  // Uses runtime lookup by activity name to support different DB environments
  await db.transaction().execute(async (trx) => {
    const activity_kualitas_pangan = await trx
      .selectFrom("ws_activities")
      .select("id")
      .where("name", "=", "Kualitas pangan")
      .executeTakeFirst()

    if (activity_kualitas_pangan) {
      await trx
        .insertInto("ws_activity_environmental_parameter_categories" as any)
        .values([
          {
            activity_id: activity_kualitas_pangan!.id,
            environmental_parameter_categories_id: 5,
          },
          {
            activity_id: activity_kualitas_pangan!.id,
            environmental_parameter_categories_id: 3,
          },
          {
            activity_id: activity_kualitas_pangan!.id,
            environmental_parameter_categories_id: 1,
          },
          {
            activity_id: activity_kualitas_pangan!.id,
            environmental_parameter_categories_id: 2,
          },
          {
            activity_id: activity_kualitas_pangan!.id,
            environmental_parameter_categories_id: 8,
          },
        ])
        .execute()
    }

    const activity_kualitas_air = await trx
      .selectFrom("ws_activities")
      .select("id")
      .where("name", "=", "Kualitas air")
      .executeTakeFirst()

    if (activity_kualitas_air) {
      await trx
        .insertInto("ws_activity_environmental_parameter_categories" as any)
        .values([
          {
            activity_id: activity_kualitas_air!.id,
            environmental_parameter_categories_id: 2,
          },
          {
            activity_id: activity_kualitas_air!.id,
            environmental_parameter_categories_id: 8,
          },
        ])
        .execute()
    }

    const activity_pemeriksaan_air_ = await trx
      .selectFrom("ws_activities")
      .select("id")
      .where("name", "=", "Pemeriksaan Air")
      .executeTakeFirst()

    if (activity_pemeriksaan_air_) {
      await trx
        .insertInto("ws_activity_environmental_parameter_categories" as any)
        .values([
          {
            activity_id: activity_pemeriksaan_air_!.id,
            environmental_parameter_categories_id: 11,
          },
        ])
        .execute()
    }

    const activity_pemeriksaan_udara = await trx
      .selectFrom("ws_activities")
      .select("id")
      .where("name", "=", "Pemeriksaan Udara")
      .executeTakeFirst()

    if (activity_pemeriksaan_udara) {
      await trx
        .insertInto("ws_activity_environmental_parameter_categories" as any)
        .values([
          {
            activity_id: activity_pemeriksaan_udara!.id,
            environmental_parameter_categories_id: 10,
          },
          {
            activity_id: activity_pemeriksaan_udara!.id,
            environmental_parameter_categories_id: 12,
          },
        ])
        .execute()
    }
  })
}

export async function down(db: Kysely<Database>): Promise<void> {
  await db
    .deleteFrom("ws_activity_environmental_parameter_categories" as any)
    .execute()
  await db
    .deleteFrom("ws_environmental_parameter_category_details" as any)
    .execute()
  await db.deleteFrom("environmental_parameter_options" as any).execute()
  await db
    .deleteFrom("environmental_parameter_validation_rules" as any)
    .execute()
  await db
    .deleteFrom("environmental_parameter_categories_fields" as any)
    .execute()
  await db.deleteFrom("environmental_test_methods" as any).execute()
  await db.deleteFrom("environmental_analysis_parameters" as any).execute()
  await db.deleteFrom("environmental_parameter_categories" as any).execute()
  await db.deleteFrom("environmental_units" as any).execute()
}
