export enum ProviderTypeTP {
  TRANSPORTER = 'TRANSPORTER',
  LANDFILLER = 'LANDFILLER',
  TREATMENT = 'TREATMENT',
  RECYCLER = 'RECYCLER',
  SPECIALIZED = 'SPECIALIZED',
  GOVERNMENT = 'GOVERNMENT',
  GOVERNMENT_WASTE_BANK = 'GOVERNMENT_WASTE_BANK',
}
