import { Kysely } from "kysely"
import { Database } from "../types/index.js"

export async function seed(db: Kysely<Database>): Promise<void> {
  const tableName = "occupations"

  const occupations = [
    { id: 1, title: "BELUM/TIDAK BEKERJA" },
    { id: 2, title: "PEGAWAI NEGERI SIPIL" },
    { id: 3, title: "TENTARA NASIONAL INDONESIA" },
    { id: 4, title: "KEPOLISIAN RI" },
    { id: 5, title: "KARYAWAN BUMN" },
    { id: 6, title: "KARYAWAN BUMD" },
    { id: 7, title: "ANGGOTA DPR-RI" },
    { id: 8, title: "ANGGOTA DPD" },
    { id: 9, title: "ANGGOTA BPK" },
    { id: 10, title: "PRESIDEN" },
    { id: 11, title: "WAKIL PRESIDEN" },
    { id: 12, title: "ANGGOTA MAHKAMAH KONSTITUSI" },
    { id: 13, title: "ANGGOTA KABINET/KEMENTERIAN" },
    { id: 14, title: "DUTA BESAR" },
    { id: 15, title: "GUBERNUR" },
    { id: 16, title: "WAKIL GUBERNUR" },
    { id: 17, title: "BUPATI" },
    { id: 18, title: "WAKIL BUPATI" },
    { id: 19, title: "WALIKOTA" },
    { id: 20, title: "WAKIL WALIKOTA" },
    { id: 21, title: "ANGGOTA DPRD PROVINSI" },
    { id: 22, title: "ANGGOTA DPRD KABUPATEN/KOTA" },
    { id: 23, title: "PENGACARA" },
    { id: 24, title: "NOTARIS" },
    { id: 25, title: "PENELITI" },
    { id: 26, title: "PERANGKAT DESA" },
    { id: 27, title: "KEPALA DESA" },
    { id: 28, title: "DOSEN" },
    { id: 29, title: "GURU" },
    { id: 30, title: "PERDAGANGAN" },
    { id: 31, title: "INDUSTRI" },
    { id: 32, title: "KONSTRUKSI" },
    { id: 33, title: "TRANSPORTASI" },
    { id: 34, title: "KARYAWAN SWASTA" },
    { id: 35, title: "KARYAWAN HONORER" },
    { id: 36, title: "BURUH HARIAN LEPAS" },
    { id: 37, title: "PEMBANTU RUMAH TANGGA" },
    { id: 38, title: "TUKANG CUKUR" },
    { id: 39, title: "TUKANG LISTRIK" },
    { id: 40, title: "TUKANG BATU" },
    { id: 41, title: "TUKANG KAYU" },
    { id: 42, title: "TUKANG SOL SEPATU" },
    { id: 43, title: "TUKANG LAS/PANDAI BESI" },
    { id: 44, title: "TUKANG JAHIT" },
    { id: 45, title: "TUKANG GIGI" },
    { id: 46, title: "PENATA RIAS" },
    { id: 47, title: "PENATA BUSANA" },
    { id: 48, title: "PENATA RAMBUT" },
    { id: 49, title: "MEKANIK" },
    { id: 50, title: "SENIMAN" },
    { id: 51, title: "TABIB" },
    { id: 52, title: "PARAJI" },
    { id: 53, title: "PERANCANG BUSANA" },
    { id: 54, title: "PENTERJEMAH" },
    { id: 55, title: "WARTAWAN" },
    { id: 56, title: "JURU MASAK" },
    { id: 57, title: "PROMOTOR ACARA" },
    { id: 58, title: "PILOT" },
    { id: 59, title: "ARSITEK" },
    { id: 60, title: "AKUNTAN" },
    { id: 61, title: "KONSULTAN" },
    { id: 62, title: "PENYIAR TELEVISI" },
    { id: 63, title: "PENYIAR RADIO" },
    { id: 64, title: "PELAUT" },
    { id: 65, title: "SOPIR" },
    { id: 66, title: "PIALANG" },
    { id: 67, title: "PARANORMAL" },
    { id: 68, title: "PEDAGANG" },
    { id: 69, title: "WIRASWASTA" },
    { id: 70, title: "PETANI/PEKEBUN" },
    { id: 71, title: "PETERNAK" },
    { id: 72, title: "BURUH TANI/PERKEBUNAN" },
    { id: 73, title: "BURUH PETERNAKAN" },
    { id: 74, title: "NELAYAN/PERIKANAN" },
    { id: 75, title: "BURUH NELAYAN/PERIKANAN" },
    { id: 76, title: "IMAM MESJID" },
    { id: 77, title: "PENDETA" },
    { id: 78, title: "PASTOR" },
    { id: 79, title: "USTADZ/MUBALIGH" },
    { id: 80, title: "BIARAWATI" },
    { id: 81, title: "PELAJAR/MAHASISWA" },
    { id: 82, title: "DOKTER" },
    { id: 83, title: "BIDAN" },
    { id: 84, title: "PERAWAT" },
    { id: 85, title: "APOTEKER" },
    { id: 86, title: "PSIKIATER/PSIKOLOG" },
    { id: 87, title: "PENSIUNAN" },
    { id: 88, title: "MENGURUS RUMAH TANGGA" },
    { id: 89, title: "LAINNYA" },
  ]

  for (const occupation of occupations) {
    await db
      .insertInto(tableName)
      .values(occupation)
      .onDuplicateKeyUpdate({
        title: occupation.title,
      })
      .execute()
  }
}
