CREATE TABLE mysql_ws_transaction_lists on cluster '{cluster}'
ENGINE = MySQL('mysql:3306', 'testdb', 'ws_transaction_lists', 'user', 'password');

CREATE TABLE ws_transaction_lists on cluster '{cluster}'
(
    `transaction_id` Int64,
    `entity_id` Nullable(Int64),
    `entity_name` Nullable(String),
    `entity_tag_id` Nullable(Int64),
    `province_id` Nullable(Int64),
    `province_name` Nullable(String),
    `regency_id` Nullable(Int64),
    `regency_name` Nullable(String),
    `companion_entity_id` Nullable(Int64),
    `companion_entity_name` Nullable(String),
    `parent_material_id` Nullable(Int64),
    `parent_material_name` Nullable(String),
    `material_id` Nullable(Int64),
    `material_name` Nullable(String),
    `material_description` Nullable(String),
    `material_is_open_vial` Nullable(Int8),
    `material_is_managed_in_batch` Nullable(Int8),
    `material_type_id` Nullable(Int64),
    `material_type_name` Nullable(String),
    `activity_id` Nullable(Int64),
    `activity_name` Nullable(String),
    `program_id` Nullable(Int32),
    `transaction_type_id` Nullable(Int64),
    `transaction_type_title` Nullable(String),
    `transaction_change_type` Nullable(String),
    `transaction_reason_id` Nullable(Int64),
    `transaction_reason_title` Nullable(String),
    `transaction_reason_is_other` Nullable(Int8),
    `transaction_reason_is_purchase` Nullable(Int8),
    `other_reason` Nullable(String),
    `order_id` Nullable(Int64),
    `order_status` Nullable(Int32),
    `order_status_label` Nullable(String),
    `order_type` Nullable(Int32),
    `order_type_label` Nullable(String),
    `vendor_id` Nullable(Int64),
    `vendor_name` Nullable(String),
    `customer_id` Nullable(Int64),
    `customer_name` Nullable(String),
    `customer_entity_tag_id` Nullable(Int64),
    `consumption_id` Nullable(Int64),
    `vaccine_method` Nullable(Int16),
    `vaccine_sequence_id` Nullable(Int64),
    `patient_id` Nullable(Int64),
    `patient_identity_type` Nullable(Int16),
    `opening_qty` Nullable(Float64),
    `change_qty` Nullable(Float64),
    `closing_qty` Nullable(Float64),
    `device_type` Nullable(Int16),
    `actual_transaction_date` Nullable(DateTime),
    `created_at` DateTime,
    `updated_at` DateTime,
    `created_by_id` Nullable(Int64),
    `created_by_username` Nullable(String),
    `created_by_firstname` Nullable(String),
    `created_by_lastname` Nullable(String),
    `updated_by_id` Nullable(Int64),
    `updated_by_username` Nullable(String),
    `updated_by_firstname` Nullable(String),
    `updated_by_lastname` Nullable(String),
    `purchase_id` Nullable(Int64),
    `purchase_year` Nullable(Int32),
    `purchase_price` Nullable(Float64),
    `budget_source_id` Nullable(Int64),
    `budget_source_name` Nullable(String),
    `stock_id` Nullable(Int64),
    `stock_open_vial` Nullable(Float64),
    `stock_close_vial` Nullable(Float64),
    `stock_allocated_qty` Nullable(Float64),
    `stock_activity_id` Nullable(Int64),
    `stock_activity_name` Nullable(String),
    `batch_id` Nullable(Int64),
    `batch_code` Nullable(String),
    `batch_expired_date` Nullable(DateTime),
    `batch_production_date` Nullable(DateTime),
    `batch_status` Nullable(Int8),
    `manufacture_id` Nullable(Int64),
    `manufacture_name` Nullable(String),
    `manufacture_address` Nullable(String),
    `patient_data` Nullable(String),
    `companion_program_id` Nullable(Int64),
    `companion_program_name` Nullable(String),
    `companion_activity_id` Nullable(Int64),
    `companion_activity_name` Nullable(String),
    `change_qty_open_vial` Float64,
    `entity_is_open_vial` Nullable(Int64),
)
ENGINE = ReplacingMergeTree
ORDER BY transaction_id;

CREATE MATERIALIZED VIEW IF NOT EXISTS ws_transaction_lists_view on cluster '{cluster}'
REFRESH EVERY 30 SECONDS APPEND TO ws_transaction_lists AS
select * from mysql_ws_transaction_lists t
WHERE t.transaction_id > (SELECT max(transaction_id) FROM ws_transaction_lists)
AND t.transaction_id <= (SELECT max(transaction_id) FROM ws_transaction_lists) + 100
ORDER BY t.transaction_id;
