sonar.projectKey=smile-platform-backend
sonar.qualitygate.wait=true

# Sources
sonar.sources=apps/core/src,apps/main/src,apps/warehouse-service/src
sonar.tests=apps/core/src/tests,apps/main/src/tests,apps/warehouse-service/src/tests
sonar.test.inclusions=apps/core/src/tests/**/*.test.ts,apps/main/src/tests/**/*.test.ts,apps/warehouse-service/src/tests/**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,apps/core/src/tests/**,apps/main/src/tests/**,apps/warehouse-service/src/tests/**

# Encoding
sonar.sourceEncoding=UTF-8

# Coverage — produced by unit-test CI job
sonar.javascript.lcov.reportPaths=apps/core/coverage/lcov.info,apps/main/coverage/lcov.info,apps/warehouse-service/coverage/lcov.info
sonar.typescript.lcov.reportPaths=apps/core/coverage/lcov.info,apps/main/coverage/lcov.info,apps/warehouse-service/coverage/lcov.info
sonar.coverage.exclusions=apps/core/src/tests/**,apps/main/src/tests/**,apps/warehouse-service/src/tests/**
