import type { Kysely } from 'kysely'

const ACTIVITIES_DATA = [
  {
    id: 1,
    program_id: 3,
    name: 'Malaria - Rutin',
    is_ordered_sales: 1,
    is_ordered_purchase: 1,
    is_final_distribution: null,
    protocol: 'default',
    status: 1,
    code: 'malaria',
  },
  {
    id: 2,
    program_id: 3,
    name: 'Malaria - MBS',
    is_ordered_sales: 1,
    is_ordered_purchase: 1,
    is_final_distribution: null,
    protocol: 'default',
    status: 1,
    code: 'mbs',
  },
  {
    id: 3,
    program_id: 4,
    name: 'TB - Program',
    is_ordered_sales: 1,
    is_ordered_purchase: 1,
    is_final_distribution: null,
    protocol: 'default',
    status: 1,
    code: 'tb',
  },
  {
    id: 4,
    program_id: 5,
    name: 'HIV - Program',
    is_ordered_sales: 1,
    is_ordered_purchase: 1,
    is_final_distribution: null,
    protocol: 'default',
    status: 1,
    code: 'hiv',
  },
  {
    id: 5,
    program_id: 6,
    name: 'Obat - PKD',
    is_ordered_sales: 1,
    is_ordered_purchase: 1,
    is_final_distribution: null,
    protocol: 'default',
    status: 1,
    code: 'pkd',
  },
  {
    id: 7,
    program_id: 4,
    name: 'TB SO',
    is_ordered_sales: 1,
    is_ordered_purchase: 1,
    is_final_distribution: null,
    protocol: 'default',
    status: 1,
    code: 'tbso',
  },
  {
    id: 8,
    program_id: 4,
    name: 'TB RO',
    is_ordered_sales: 1,
    is_ordered_purchase: 1,
    is_final_distribution: null,
    protocol: 'default',
    status: 1,
    code: 'tbro',
  },
  {
    id: 9,
    program_id: 4,
    name: 'TB TPT',
    is_ordered_sales: 1,
    is_ordered_purchase: 1,
    is_final_distribution: null,
    protocol: 'default',
    status: 1,
    code: 'tbtpt',
  },
  {
    id: 10,
    program_id: 4,
    name: 'TB Non OAT',
    is_ordered_sales: 1,
    is_ordered_purchase: 1,
    is_final_distribution: null,
    protocol: 'default',
    status: 1,
    code: 'tbnoat',
  },
  {
    id: 26,
    program_id: 2,
    name: 'Rutin',
    is_ordered_sales: 1,
    is_ordered_purchase: 1,
    is_final_distribution: null,
    protocol: 'default',
    status: 1,
    code: 'rutin',
  },
  {
    id: 27,
    program_id: 2,
    name: 'BIAS',
    is_ordered_sales: 1,
    is_ordered_purchase: 1,
    is_final_distribution: null,
    protocol: 'default',
    status: 1,
    code: 'bias',
  },
  {
    id: 28,
    program_id: 2,
    name: 'ORI',
    is_ordered_sales: 1,
    is_ordered_purchase: 1,
    is_final_distribution: null,
    protocol: 'default',
    status: 1,
    code: 'ori',
  },
  {
    id: 29,
    program_id: 2,
    name: 'Kampanye',
    is_ordered_sales: 1,
    is_ordered_purchase: 1,
    is_final_distribution: null,
    protocol: 'default',
    status: 1,
    code: 'campaign',
  },
  {
    id: 30,
    program_id: 2,
    name: 'COVID-19',
    is_ordered_sales: 1,
    is_ordered_purchase: 1,
    is_final_distribution: null,
    protocol: 'default',
    status: 1,
    code: 'covid',
  },
  {
    id: 31,
    program_id: 2,
    name: 'BIAN',
    is_ordered_sales: 1,
    is_ordered_purchase: 1,
    is_final_distribution: null,
    protocol: 'default',
    status: 1,
    code: 'bian',
  },
  {
    id: 32,
    program_id: 2,
    name: 'Lanjutan & Khusus',
    is_ordered_sales: 1,
    is_ordered_purchase: 1,
    is_final_distribution: null,
    protocol: 'default',
    status: 1,
    code: 'extended',
  },
  {
    id: 33,
    program_id: 6,
    name: 'Rabies',
    is_ordered_sales: 1,
    is_ordered_purchase: 1,
    is_final_distribution: null,
    protocol: 'default',
    status: 1,
    code: 'rabies',
  },
  {
    id: 38,
    program_id: 2,
    name: 'PD3I',
    is_ordered_sales: 1,
    is_ordered_purchase: 1,
    is_final_distribution: null,
    protocol: 'default',
    status: 1,
    code: null,
  },
]

export async function seed(db: Kysely<any>): Promise<void> {
  console.log(`Seeding ${ACTIVITIES_DATA.length} activities...`)

  for (const activity of ACTIVITIES_DATA) {
    await db
      .insertInto('ws_activities')
      .values({
        id: activity.id,
        program_id: activity.program_id,
        name: activity.name,
        is_ordered_sales: activity.is_ordered_sales,
        is_ordered_purchase: activity.is_ordered_purchase,
        is_final_distribution: activity.is_final_distribution,
        protocol: activity.protocol,
        status: activity.status,
        code: activity.code,
      })
      .onDuplicateKeyUpdate({
        name: activity.name,
        is_ordered_sales: activity.is_ordered_sales,
        is_ordered_purchase: activity.is_ordered_purchase,
        is_final_distribution: activity.is_final_distribution,
        protocol: activity.protocol,
        status: activity.status,
        code: activity.code,
        updated_at: new Date(),
      })
      .execute()
  }

  console.log(`✅ Successfully seeded ${ACTIVITIES_DATA.length} activities`)
}
