export interface EventList {
    WASTE_BAG_CREATED: 'WASTE_BAG_CREATED';
    WASTE_BAG_TEMPORARY_STORED: 'WASTE_BAG_TEMPORARY_STORED';
    WASTE_BAG_COLD_STORED_STARTED: 'WASTE_BAG_COLD_STORED_STARTED';
    WASTE_BAG_COLD_STORED_ENDED: 'WASTE_BAG_COLD_STORED_ENDED';
    WASTE_BAG_INCINERATION_STARTED: 'WASTE_BAG_INCINERATION_STARTED';
    WASTE_BAG_INCINERATED: 'WASTE_BAG_INCINERATED';
    WASTE_BAG_STERILISED_STARTED: 'WASTE_BAG_STERILISED_STARTED';
    WASTE_BAG_STERILISED: 'WASTE_BAG_STERILISED';
    WASTE_BAG_FOLLOW_UP_TO_TRANSPORTER: 'WASTE_BAG_FOLLOW_UP_TO_TRANSPORTER';
    WASTE_BAG_FOLLOW_UP_TO_TRANSPORTER_EXTERNAL: 'WASTE_BAG_FOLLOW_UP_TO_TRANSPORTER_EXTERNAL';
    WASTE_BAG_HANDOVER_TO_TRANSPORTER: 'WASTE_BAG_HANDOVER_TO_TRANSPORTER';
    WASTE_BAG_HANDOVER_TO_TRANSPORTER_EXTERNAL: 'WASTE_BAG_HANDOVER_TO_TRANSPORTER_EXTERNAL';
    WASTE_BAG_READY_FOR_TRANSPORT: 'WASTE_BAG_READY_FOR_TRANSPORT';
    WASTE_BAG_READY_IN_TRANSIT: 'WASTE_BAG_READY_IN_TRANSIT';
    WASTE_BAG_PICKUP_TO_TRANSPORTER_EXTERNAL: 'WASTE_BAG_PICKUP_TO_TRANSPORTER_EXTERNAL';
    WASTE_BAG_HANDOVER_TO_TREATMENT_EXTERNAL: 'WASTE_BAG_HANDOVER_TO_TREATMENT_EXTERNAL';
    WASTE_BAG_ALREADY_TREATED_IN_THIRD_PARTY: 'WASTE_BAG_ALREADY_TREATED_IN_THIRD_PARTY';
}

export interface EventListFailed {
    WASTE_BAG_COLD_STORAGE_FAILED: 'WASTE_BAG_COLD_STORAGE_FAILED';
    WASTE_BAG_TEMPORARY_STORAGE_FAILED: 'WASTE_BAG_TEMPORARY_STORAGE_FAILED';
    WASTE_BAG_STERILISED_STARTED_FAILED: 'WASTE_BAG_STERILISED_STARTED_FAILED';
    WASTE_BAG_INCINERATION_FAILED: 'WASTE_BAG_INCINERATION_FAILED';
    WASTE_BAG_FOLLOW_UP_TO_TRANSPORTER_FAILED: 'WASTE_BAG_FOLLOW_UP_TO_TRANSPORTER_FAILED';
    WASTE_BAG_FOLLOW_UP_TO_TRANSPORTER_EXTERNAL_FAILED: 'WASTE_BAG_FOLLOW_UP_TO_TRANSPORTER_EXTERNAL_FAILED';
    WASTE_BAG_HANDOVER_TO_TRANSPORTER_FAILED: 'WASTE_BAG_HANDOVER_TO_TRANSPORTER_FAILED';
    WASTE_BAG_HANDOVER_TO_TRANSPORTER_EXTERNAL_FAILED: 'WASTE_BAG_HANDOVER_TO_TRANSPORTER_EXTERNAL_FAILED';
    WASTE_BAG_PICKUP_TO_TRANSPORTER_EXTERNAL_FAILED: 'WASTE_BAG_PICKUP_TO_TRANSPORTER_EXTERNAL_FAILED';
    WASTE_BAG_HANDOVER_TO_TREATMENT_EXTERNAL_FAILED: 'WASTE_BAG_HANDOVER_TO_TREATMENT_EXTERNAL_FAILED';
}

/*
1EX - Transport Treatment
2EX - Transport Landfill
3EX - Transport Recycle
4EX - Spesialized Treatment

1IN - Temporary Storage
2IN - Cold Storage
3IN - Inceneration / Pyrolis
4IN - Sterilisation / Disinfection
*/
