const sampleOrderDetail = {
  id: 184299,
  device_type: 1,
  customer_id: 10336,
  vendor_id: 26,
  status: 2,
  type: 1,
  required_date: '2025-06-19T00:00:00.000Z',
  estimated_date: null,
  actual_shipment_date: null,
  purchase_ref: null,
  sales_ref: null,
  delivery_number: null,
  confirmed_at: '2025-06-19T04:58:15.000Z',
  shipped_at: null,
  fulfilled_at: null,
  cancelled_at: null,
  allocated_at: null,
  created_at: '2025-06-19T04:57:29.000Z',
  updated_at: '2025-06-19T04:58:15.000Z',
  deleted_at: null,
  taken_by_customer: 0,
  delivery_type: null,
  doc_no: null,
  notes: null,
  po_no: null,
  total_order_items: 3,
  is_allocated: 1,
  other_reason_cancel: null,
  order_cancel_reason: null,
  activity: {
    id: 11,
    name: 'Malaria - Rutin',
  },
  order_comments: [
    {
      id: 103473,
      comment: 'mantap',
      created_at: '2025-06-19T04:58:15.000Z',
      order_status: 2,
      user: {
        id: 31496,
        firstname: 'gilang12',
        lastname: null,
      },
    },
    {
      id: 103472,
      comment: 'Mantap',
      created_at: '2025-06-19T04:57:30.000Z',
      order_status: 1,
      user: {
        id: 32259,
        firstname: 'Super222',
        lastname: 'Program',
      },
    },
  ],
  customer: {
    id: 10336,
    name: 'PUSKESMAS BOJONGSARI',
    address: 'Komp. Pamulang Village Blok H8',
    type: 3,
    status: 1,
  },
  vendor: {
    id: 26,
    name: 'DINKES KOTA DEPOK',
    address: '-',
    type: 2,
    status: 1,
  },
  order_items: [
    {
      id: 287525,
      order_id: 184299,
      recommended_stock: 0,
      qty: 200,
      ordered_qty: 10,
      confirmed_qty: 200,
      other_reason: null,
      created_at: '2025-06-19T04:57:30.000Z',
      reason: {
        id: 9,
        name: 'Lainnya',
      },
      material: {
        id: 3173,
        name: 'Jamu',
        code: '921905202501',
        type: 'medicine',
        kfa_level_id: null,
        kfa_level_name: null,
        unit_of_consumption: 'pcs',
        unit_of_distribution: 'box',
        consumption_unit_per_distribution_unit: 1,
        is_managed_in_batch: 1,
        is_temperature_sensitive: 0,
        material_level_id: 2,
        parent_id: null,
      },
      order_stocks: [],
      stock_customer: {
        program_id: 2,
        entity_id: 10336,
        total_qty: 5070,
        total_in_transit_qty: 0,
        total_allocated_qty: 0,
        total_available_qty: 5070,
        total_unreceived_qty: 910,
        material_id: 3173,
        min: null,
        max: null,
      },
      stock_vendor: {
        program_id: 2,
        entity_id: 26,
        total_qty: 5193885,
        total_in_transit_qty: 975,
        total_allocated_qty: 10,
        total_available_qty: 5193875,
        total_unreceived_qty: 0,
        material_id: 3173,
        min: 0,
        max: 0,
      },
      children: [
        {
          id: 287526,
          order_id: 184299,
          recommended_stock: null,
          qty: 200,
          ordered_qty: 10,
          confirmed_qty: 200,
          other_reason: null,
          created_at: '2025-06-19T04:57:30.000Z',
          reason: null,
          material: {
            id: 3175,
            name: 'Madurasa 100ml',
            code: '931905202502',
            type: 'medicine',
            kfa_level_id: null,
            kfa_level_name: null,
            unit_of_consumption: 'ml',
            unit_of_distribution: 'vial',
            consumption_unit_per_distribution_unit: 1,
            is_managed_in_batch: 1,
            is_temperature_sensitive: 0,
            material_level_id: 3,
            parent_id: 3173,
          },
          order_stocks: [],
          stock_customer: {
            program_id: 2,
            entity_id: 10336,
            total_qty: 5140,
            total_in_transit_qty: 0,
            total_allocated_qty: 0,
            total_available_qty: 5140,
            total_unreceived_qty: 910,
            material_id: 3175,
            price: 0,
            min: null,
            max: null,
          },
          stock_vendor: {
            program_id: 2,
            entity_id: 26,
            total_qty: 2193885,
            total_in_transit_qty: 975,
            total_allocated_qty: 10,
            total_available_qty: 2193875,
            total_unreceived_qty: 0,
            material_id: 3175,
            price: 0,
            min: 0,
            max: 0,
          },
          allocated_qty: 0,
          shipped_qty: 0,
          fulfilled_qty: 0,
        },
      ],
      allocated_qty: 0,
      shipped_qty: 0,
      fulfilled_qty: 0,
    },
    {
      id: 287527,
      order_id: 184299,
      recommended_stock: 0,
      qty: 0,
      ordered_qty: 20,
      confirmed_qty: 0,
      other_reason: null,
      created_at: '2025-06-19T04:57:30.000Z',
      reason: {
        id: 9,
        name: 'Lainnya',
      },
      material: {
        id: 572,
        name: 'Kertas saring',
        code: '9282_Kertas saring',
        type: 'non_medical_devices',
        kfa_level_id: null,
        kfa_level_name: null,
        unit_of_consumption: 'doses',
        unit_of_distribution: 'box',
        consumption_unit_per_distribution_unit: 1,
        is_managed_in_batch: 0,
        is_temperature_sensitive: 0,
        material_level_id: 2,
        parent_id: null,
      },
      order_stocks: [],
      stock_customer: {
        program_id: 2,
        entity_id: 10336,
        total_qty: 0,
        total_in_transit_qty: 0,
        total_allocated_qty: 0,
        total_available_qty: 0,
        total_unreceived_qty: 660,
        material_id: 572,
        min: null,
        max: null,
      },
      stock_vendor: {
        program_id: 2,
        entity_id: 26,
        total_qty: 18999695,
        total_in_transit_qty: 660,
        total_allocated_qty: 30,
        total_available_qty: 18999665,
        total_unreceived_qty: 0,
        material_id: 572,
        min: 0,
        max: 0,
      },
      children: [],
      allocated_qty: 0,
      shipped_qty: 0,
      fulfilled_qty: 0,
    },
    {
      id: 287528,
      order_id: 184299,
      recommended_stock: 0,
      qty: 0,
      ordered_qty: 30,
      confirmed_qty: 0,
      other_reason: null,
      created_at: '2025-06-19T04:57:30.000Z',
      reason: {
        id: 9,
        name: 'Lainnya',
      },
      material: {
        id: 559,
        name: 'Slide Box / Slide Storage',
        code: '82000933_1',
        type: 'medical_devices',
        kfa_level_id: null,
        kfa_level_name: null,
        unit_of_consumption: 'doses',
        unit_of_distribution: 'box',
        consumption_unit_per_distribution_unit: 1,
        is_managed_in_batch: 1,
        is_temperature_sensitive: 0,
        material_level_id: 2,
        parent_id: null,
      },
      order_stocks: [],
      stock_customer: {
        program_id: 2,
        entity_id: 10336,
        total_qty: 0,
        total_in_transit_qty: 0,
        total_allocated_qty: 0,
        total_available_qty: 0,
        total_unreceived_qty: 50,
        material_id: 559,
        min: null,
        max: null,
      },
      stock_vendor: {
        program_id: 2,
        entity_id: 26,
        total_qty: 14000280,
        total_in_transit_qty: 50,
        total_allocated_qty: 0,
        total_available_qty: 14000280,
        total_unreceived_qty: 0,
        material_id: 559,
        min: 0,
        max: 0,
      },
      children: [
        {
          id: 287529,
          order_id: 184299,
          recommended_stock: null,
          qty: 0,
          ordered_qty: 30,
          confirmed_qty: 0,
          other_reason: null,
          created_at: '2025-06-19T04:57:30.000Z',
          reason: null,
          material: {
            id: 30,
            name: 'Slide Box (isi 100)',
            code: 'Slide Box',
            type: 'medical_devices',
            kfa_level_id: null,
            kfa_level_name: null,
            unit_of_consumption: 'doses',
            unit_of_distribution: 'box',
            consumption_unit_per_distribution_unit: 1,
            is_managed_in_batch: 0,
            is_temperature_sensitive: 0,
            material_level_id: 3,
            parent_id: 559,
          },
          order_stocks: [],
          stock_customer: {
            program_id: 2,
            entity_id: 10336,
            total_qty: 0,
            total_in_transit_qty: 0,
            total_allocated_qty: 0,
            total_available_qty: 0,
            total_unreceived_qty: 50,
            material_id: 30,
            price: 0,
            min: null,
            max: null,
          },
          stock_vendor: {
            program_id: 2,
            entity_id: 26,
            total_qty: 9000170,
            total_in_transit_qty: 50,
            total_allocated_qty: 0,
            total_available_qty: 9000170,
            total_unreceived_qty: 0,
            material_id: 30,
            price: 0,
            min: 0,
            max: 0,
          },
          allocated_qty: 0,
          shipped_qty: 0,
          fulfilled_qty: 0,
        },
      ],
      allocated_qty: 0,
      shipped_qty: 0,
      fulfilled_qty: 0,
    },
  ],
  user_confirmed_by: {
    id: 31496,
    firstname: 'gilang12',
    lastname: null,
  },
  user_shipped_by: null,
  user_fulfilled_by: null,
  user_cancelled_by: null,
  user_allocated_by: null,
  user_created_by: {
    id: 32259,
    firstname: 'Super222',
    lastname: 'Program',
  },
  user_updated_by: {
    id: 31496,
    firstname: 'gilang12',
    lastname: null,
  },
  user_deleted_by: null,
}
const sampeVendorStockResponseData = {
  page: 1,
  item_per_page: 100,
  total_item: 3,
  total_page: 1,
  list_pagination: [10, 25, 50, 100],
  data: [
    {
      total_qty: 4198960,
      total_allocated_qty: 0,
      total_in_transit_qty: 950,
      total_unreceived_qty: 0,
      total_open_vial_qty: 0,
      total_available_qty: 4198960,
      updated_at: '2025-06-19 04:50:58',
      last_opname_date: null,
      min: 0,
      max: 0,
      aggregate: {
        total_qty: 5193885,
        total_allocated_qty: 10,
        total_in_transit_qty: 975,
        total_unreceived_qty: 0,
        total_open_vial_qty: 0,
        total_available_qty: 5193875,
        updated_at: '2025-06-19 04:50:58',
        min: 0,
        max: 0,
      },
      entity: {
        id: 26,
        name: 'DINKES KOTA DEPOK',
        type: 2,
        address: '-',
        tag: 'Dinas Kesehatan KabKota',
        location: 'KOTA DEPOK, PROV. JAWA BARAT',
      },
      material: {
        id: 3173,
        name: 'Jamu',
        material_level_id: 2,
        is_temperature_sensitive: 0,
        is_open_vial: 0,
        is_managed_in_batch: 1,
        unit_of_consumption: 'pcs',
        consumption_unit_per_distribution_unit: 1,
        status: 1,
        companions: [],
        activities: [
          {
            id: 13,
            name: 'Malaria - MBS',
          },
          {
            id: 11,
            name: 'Malaria - Rutin',
          },
          {
            id: 14,
            name: 'TB - Program',
          },
        ],
      },
      activity: {
        id: 11,
        name: 'Malaria - Rutin',
      },
      protocol: {
        key: 'default',
        material_id: 3173,
        activity_id: 11,
        is_sequence: 0,
        is_patient_needed: 0,
      },
      details: [
        {
          activity: null,
          material: {
            id: 3174,
            name: 'Buyung Upik',
            material_level_id: 3,
            is_temperature_sensitive: 0,
            is_open_vial: 0,
            is_managed_in_batch: 1,
            unit_of_consumption: 'pcs',
            consumption_unit_per_distribution_unit: 1,
            status: 1,
            companions: [],
            activities: [
              {
                id: 11,
                name: 'Malaria - Rutin',
              },
              {
                id: 13,
                name: 'Malaria - MBS',
              },
              {
                id: 14,
                name: 'TB - Program',
              },
            ],
          },
          total_qty: 3000000,
          total_allocated_qty: 0,
          total_in_transit_qty: 0,
          total_unreceived_qty: 0,
          total_open_vial_qty: 0,
          total_available_qty: 3000000,
          min: 0,
          max: 0,
          updated_at: '2025-06-03T09:47:18.000Z',
          last_opname_date: null,
          stocks: [
            {
              id: 362620,
              batch: {
                id: 13228,
                code: 'BATCHBUYUNGKOU001',
                production_date: '2025-06-03 00:00:00',
                expired_date: '2031-06-03 00:00:00',
                manufacture: {
                  id: 678,
                  name: 'Sidomuncul',
                  address: 'Depok Jaya Abadi',
                },
              },
              budget_source: null,
              qty: 1000000,
              allocated_qty: 0,
              in_transit_qty: 0,
              unreceived_qty: 0,
              open_vial_qty: 0,
              available_qty: 1000000,
              price: 0,
              min: 0,
              max: 0,
              total_price: 0,
              year: null,
              updated_at: '2025-06-03T09:47:18.000Z',
              activity: {
                id: 11,
                name: 'Malaria - Rutin',
              },
            },
            {
              id: 362621,
              batch: {
                id: 13229,
                code: 'BATCHBUYUNGKOU002',
                production_date: '2025-06-03 00:00:00',
                expired_date: '2031-06-03 00:00:00',
                manufacture: {
                  id: 678,
                  name: 'Sidomuncul',
                  address: 'Depok Jaya Abadi',
                },
              },
              budget_source: null,
              qty: 2000000,
              allocated_qty: 0,
              in_transit_qty: 0,
              unreceived_qty: 0,
              open_vial_qty: 0,
              available_qty: 2000000,
              price: 0,
              min: 0,
              max: 0,
              total_price: 0,
              year: null,
              updated_at: '2025-06-03T09:47:18.000Z',
              activity: {
                id: 11,
                name: 'Malaria - Rutin',
              },
            },
          ],
        },
        {
          activity: null,
          material: {
            id: 3175,
            name: 'Madurasa 100ml',
            material_level_id: 3,
            is_temperature_sensitive: 0,
            is_open_vial: 0,
            is_managed_in_batch: 1,
            unit_of_consumption: 'ml',
            consumption_unit_per_distribution_unit: 1,
            status: 1,
            companions: [],
            activities: [
              {
                id: 11,
                name: 'Malaria - Rutin',
              },
              {
                id: 13,
                name: 'Malaria - MBS',
              },
              {
                id: 14,
                name: 'TB - Program',
              },
            ],
          },
          total_qty: 1198960,
          total_allocated_qty: 0,
          total_in_transit_qty: 950,
          total_unreceived_qty: 0,
          total_open_vial_qty: 0,
          total_available_qty: 1198960,
          min: 0,
          max: 0,
          updated_at: '2025-06-19T04:50:58.000Z',
          last_opname_date: null,
          stocks: [
            {
              id: 362485,
              batch: {
                id: 13160,
                code: 'MADURASAKOURUTIN001',
                production_date: '2025-05-01 00:00:00',
                expired_date: '2031-05-31 00:00:00',
                manufacture: {
                  id: 678,
                  name: 'Sidomuncul',
                  address: 'Depok Jaya Abadi',
                },
              },
              budget_source: null,
              qty: 499570,
              allocated_qty: 0,
              in_transit_qty: 360,
              unreceived_qty: 0,
              open_vial_qty: 0,
              available_qty: 499570,
              price: 0,
              min: 0,
              max: 0,
              total_price: 0,
              year: null,
              updated_at: '2025-06-19T04:50:58.000Z',
              activity: {
                id: 11,
                name: 'Malaria - Rutin',
              },
            },
            {
              id: 362486,
              batch: {
                id: 13161,
                code: 'MADURASAKOURUTIN002',
                production_date: '2025-05-01 00:00:00',
                expired_date: '2049-05-31 00:00:00',
                manufacture: {
                  id: 678,
                  name: 'Sidomuncul',
                  address: 'Depok Jaya Abadi',
                },
              },
              budget_source: null,
              qty: 699390,
              allocated_qty: 0,
              in_transit_qty: 590,
              unreceived_qty: 0,
              open_vial_qty: 0,
              available_qty: 699390,
              price: 0,
              min: 0,
              max: 0,
              total_price: 0,
              year: null,
              updated_at: '2025-06-19T04:50:58.000Z',
              activity: {
                id: 11,
                name: 'Malaria - Rutin',
              },
            },
          ],
        },
      ],
    },
    {
      total_qty: 10999460,
      total_allocated_qty: 30,
      total_in_transit_qty: 660,
      total_unreceived_qty: 0,
      total_open_vial_qty: 0,
      total_available_qty: 10999430,
      updated_at: '2025-06-19 08:19:51',
      last_opname_date: null,
      min: 0,
      max: 0,
      aggregate: {
        total_qty: 18999695,
        total_allocated_qty: 30,
        total_in_transit_qty: 660,
        total_unreceived_qty: 0,
        total_open_vial_qty: 0,
        total_available_qty: 18999665,
        updated_at: '2025-06-19 08:19:51',
        min: 0,
        max: 0,
      },
      entity: {
        id: 26,
        name: 'DINKES KOTA DEPOK',
        type: 2,
        address: '-',
        tag: 'Dinas Kesehatan KabKota',
        location: 'KOTA DEPOK, PROV. JAWA BARAT',
      },
      material: {
        id: 572,
        name: 'Kertas saring',
        material_level_id: 2,
        is_temperature_sensitive: 0,
        is_open_vial: 0,
        is_managed_in_batch: 0,
        unit_of_consumption: 'doses',
        consumption_unit_per_distribution_unit: 1,
        status: 1,
        companions: [],
        activities: [
          {
            id: 11,
            name: 'Malaria - Rutin',
          },
          {
            id: 13,
            name: 'Malaria - MBS',
          },
          {
            id: 14,
            name: 'TB - Program',
          },
          {
            id: 15,
            name: 'HIV - Program',
          },
          {
            id: 16,
            name: 'Rabies - Program',
          },
          {
            id: 17,
            name: 'Anti Venom',
          },
          {
            id: 18,
            name: 'Contoh Aktifitas Mantab 005',
          },
        ],
      },
      activity: {
        id: 11,
        name: 'Malaria - Rutin',
      },
      protocol: {
        key: 'default',
        material_id: 572,
        activity_id: 11,
        is_sequence: 0,
        is_patient_needed: 0,
      },
      details: [
        {
          activity: null,
          material: {
            id: 46,
            name: 'Kertas Saring 125mm',
            material_level_id: 3,
            is_temperature_sensitive: 0,
            is_open_vial: 0,
            is_managed_in_batch: 0,
            unit_of_consumption: 'doses',
            consumption_unit_per_distribution_unit: 1,
            status: 1,
            companions: [],
            activities: [
              {
                id: 11,
                name: 'Malaria - Rutin',
              },
              {
                id: 12,
                name: 'Dengue',
              },
              {
                id: 13,
                name: 'Malaria - MBS',
              },
              {
                id: 14,
                name: 'TB - Program',
              },
              {
                id: 15,
                name: 'HIV - Program',
              },
              {
                id: 16,
                name: 'Rabies - Program',
              },
              {
                id: 17,
                name: 'Anti Venom',
              },
              {
                id: 18,
                name: 'Contoh Aktifitas Mantab 005',
              },
            ],
          },
          total_qty: 5999640,
          total_allocated_qty: 20,
          total_in_transit_qty: 440,
          total_unreceived_qty: 0,
          total_open_vial_qty: 0,
          total_available_qty: 5999620,
          min: 0,
          max: 0,
          updated_at: '2025-06-19T08:19:51.000Z',
          last_opname_date: null,
          stocks: [
            {
              id: 362639,
              batch: null,
              budget_source: null,
              qty: 5999640,
              allocated_qty: 20,
              in_transit_qty: 440,
              unreceived_qty: 0,
              open_vial_qty: 0,
              available_qty: 5999620,
              price: 0,
              min: 0,
              max: 0,
              total_price: 0,
              year: null,
              updated_at: '2025-06-19T08:19:51.000Z',
              activity: {
                id: 11,
                name: 'Malaria - Rutin',
              },
            },
          ],
        },
        {
          activity: null,
          material: {
            id: 47,
            name: 'Kertas Saring 110mm',
            material_level_id: 3,
            is_temperature_sensitive: 0,
            is_open_vial: 0,
            is_managed_in_batch: 0,
            unit_of_consumption: 'doses',
            consumption_unit_per_distribution_unit: 1,
            status: 1,
            companions: [],
            activities: [
              {
                id: 11,
                name: 'Malaria - Rutin',
              },
              {
                id: 12,
                name: 'Dengue',
              },
              {
                id: 13,
                name: 'Malaria - MBS',
              },
              {
                id: 14,
                name: 'TB - Program',
              },
              {
                id: 15,
                name: 'HIV - Program',
              },
              {
                id: 16,
                name: 'Rabies - Program',
              },
              {
                id: 17,
                name: 'Anti Venom',
              },
              {
                id: 18,
                name: 'Contoh Aktifitas Mantab 005',
              },
            ],
          },
          total_qty: 4999820,
          total_allocated_qty: 10,
          total_in_transit_qty: 220,
          total_unreceived_qty: 0,
          total_open_vial_qty: 0,
          total_available_qty: 4999810,
          min: 0,
          max: 0,
          updated_at: '2025-06-19T08:19:50.000Z',
          last_opname_date: null,
          stocks: [
            {
              id: 362638,
              batch: null,
              budget_source: null,
              qty: 4999820,
              allocated_qty: 10,
              in_transit_qty: 220,
              unreceived_qty: 0,
              open_vial_qty: 0,
              available_qty: 4999810,
              price: 0,
              min: 0,
              max: 0,
              total_price: 0,
              year: null,
              updated_at: '2025-06-19T08:19:50.000Z',
              activity: {
                id: 11,
                name: 'Malaria - Rutin',
              },
            },
          ],
        },
      ],
    },
    {
      total_qty: 11000130,
      total_allocated_qty: 0,
      total_in_transit_qty: 50,
      total_unreceived_qty: 0,
      total_open_vial_qty: 0,
      total_available_qty: 11000130,
      updated_at: '2025-06-11 01:41:32',
      last_opname_date: null,
      min: 0,
      max: 0,
      aggregate: {
        total_qty: 14000280,
        total_allocated_qty: 0,
        total_in_transit_qty: 50,
        total_unreceived_qty: 0,
        total_open_vial_qty: 0,
        total_available_qty: 14000280,
        updated_at: '2025-06-11 01:41:32',
        min: 0,
        max: 0,
      },
      entity: {
        id: 26,
        name: 'DINKES KOTA DEPOK',
        type: 2,
        address: '-',
        tag: 'Dinas Kesehatan KabKota',
        location: 'KOTA DEPOK, PROV. JAWA BARAT',
      },
      material: {
        id: 559,
        name: 'Slide Box / Slide Storage',
        material_level_id: 2,
        is_temperature_sensitive: 0,
        is_open_vial: 0,
        is_managed_in_batch: 1,
        unit_of_consumption: 'doses',
        consumption_unit_per_distribution_unit: 1,
        status: 1,
        companions: [],
        activities: [
          {
            id: 11,
            name: 'Malaria - Rutin',
          },
          {
            id: 13,
            name: 'Malaria - MBS',
          },
          {
            id: 14,
            name: 'TB - Program',
          },
          {
            id: 15,
            name: 'HIV - Program',
          },
          {
            id: 16,
            name: 'Rabies - Program',
          },
          {
            id: 17,
            name: 'Anti Venom',
          },
          {
            id: 18,
            name: 'Contoh Aktifitas Mantab 005',
          },
        ],
      },
      activity: {
        id: 11,
        name: 'Malaria - Rutin',
      },
      protocol: {
        key: 'default',
        material_id: 559,
        activity_id: 11,
        is_sequence: 0,
        is_patient_needed: 0,
      },
      details: [
        {
          activity: null,
          material: {
            id: 30,
            name: 'Slide Box (isi 100)',
            material_level_id: 3,
            is_temperature_sensitive: 0,
            is_open_vial: 0,
            is_managed_in_batch: 0,
            unit_of_consumption: 'doses',
            consumption_unit_per_distribution_unit: 1,
            status: 1,
            companions: [],
            activities: [
              {
                id: 11,
                name: 'Malaria - Rutin',
              },
              {
                id: 12,
                name: 'Dengue',
              },
              {
                id: 13,
                name: 'Malaria - MBS',
              },
              {
                id: 14,
                name: 'TB - Program',
              },
              {
                id: 15,
                name: 'HIV - Program',
              },
              {
                id: 16,
                name: 'Rabies - Program',
              },
              {
                id: 17,
                name: 'Anti Venom',
              },
              {
                id: 18,
                name: 'Contoh Aktifitas Mantab 005',
              },
            ],
          },
          total_qty: 7000070,
          total_allocated_qty: 0,
          total_in_transit_qty: 50,
          total_unreceived_qty: 0,
          total_open_vial_qty: 0,
          total_available_qty: 7000070,
          min: 0,
          max: 0,
          updated_at: '2025-06-11T01:41:32.000Z',
          last_opname_date: null,
          stocks: [
            {
              id: 362640,
              batch: null,
              budget_source: null,
              qty: 7000070,
              allocated_qty: 0,
              in_transit_qty: 50,
              unreceived_qty: 0,
              open_vial_qty: 0,
              available_qty: 7000070,
              price: 0,
              min: 0,
              max: 0,
              total_price: 0,
              year: null,
              updated_at: '2025-06-11T01:41:32.000Z',
              activity: {
                id: 11,
                name: 'Malaria - Rutin',
              },
            },
          ],
        },
        {
          activity: null,
          material: {
            id: 43,
            name: 'Slide Box (isi 50)',
            material_level_id: 3,
            is_temperature_sensitive: 0,
            is_open_vial: 0,
            is_managed_in_batch: 0,
            unit_of_consumption: 'doses',
            consumption_unit_per_distribution_unit: 1,
            status: 1,
            companions: [],
            activities: [
              {
                id: 11,
                name: 'Malaria - Rutin',
              },
              {
                id: 12,
                name: 'Dengue',
              },
              {
                id: 13,
                name: 'Malaria - MBS',
              },
              {
                id: 14,
                name: 'TB - Program',
              },
              {
                id: 15,
                name: 'HIV - Program',
              },
              {
                id: 16,
                name: 'Rabies - Program',
              },
              {
                id: 17,
                name: 'Anti Venom',
              },
              {
                id: 18,
                name: 'Contoh Aktifitas Mantab 005',
              },
            ],
          },
          total_qty: 4000060,
          total_allocated_qty: 0,
          total_in_transit_qty: 0,
          total_unreceived_qty: 0,
          total_open_vial_qty: 0,
          total_available_qty: 4000060,
          min: 0,
          max: 0,
          updated_at: '2025-06-10T09:14:45.000Z',
          last_opname_date: null,
          stocks: [
            {
              id: 362641,
              batch: null,
              budget_source: null,
              qty: 4000060,
              allocated_qty: 0,
              in_transit_qty: 0,
              unreceived_qty: 0,
              open_vial_qty: 0,
              available_qty: 4000060,
              price: 0,
              min: 0,
              max: 0,
              total_price: 0,
              year: null,
              updated_at: '2025-06-10T09:14:45.000Z',
              activity: {
                id: 11,
                name: 'Malaria - Rutin',
              },
            },
          ],
        },
      ],
    },
  ],
}
