export const dummy = {
  id: 127,
  material_id: 105,
  entity_id: 22317,
  activity_id: 6,
  start_date: '2025-01-16T00:00:00.000Z',
  end_date: '2025-01-23T00:00:00.000Z',
  deleted_at: null,
  created_by: 48514,
  updated_by: null,
  deleted_by: null,
  created_at: '2025-01-23T07:06:05.000Z',
  updated_at: '2025-01-23T07:06:05.000Z',
  entity: {
    id: 22317,
    name: 'PUSKESMAS JUMO',
  },
  material: {
    id: 105,
    name: 'Material Non Batch JK',
    code: '771346jy11',
  },
  activity: {
    id: 6,
    name: 'COVID-19',
  },
  user_created_by: {
    id: 48514,
    username: 'rayhan',
    email: 'rayhan@gmail.com',
    firstname: 'rayhan',
    lastname: null,
  },
  user_updated_by: null,
  reconciliation_items: [
    {
      id: 834,
      reconciliation_id: 127,
      stock_category: 1,
      smile_qty: 0,
      real_qty: 0,
      stock_category_label: 'Penerimaan',
      reasons: [],
      actions: [],
    },
    {
      id: 835,
      reconciliation_id: 127,
      stock_category: 2,
      smile_qty: 0,
      real_qty: 0,
      stock_category_label: 'Pengembalian Distribusi',
      reasons: [],
      actions: [],
    },
    {
      id: 836,
      reconciliation_id: 127,
      stock_category: 3,
      smile_qty: 0,
      real_qty: 0,
      stock_category_label: 'Distribusi',
      reasons: [],
      actions: [],
    },
    {
      id: 837,
      reconciliation_id: 127,
      stock_category: 4,
      smile_qty: 0,
      real_qty: 0,
      stock_category_label: 'Penerimaan Pengembalian',
      reasons: [],
      actions: [],
    },
    {
      id: 838,
      reconciliation_id: 127,
      stock_category: 5,
      smile_qty: 0,
      real_qty: 0,
      stock_category_label: 'Konsumsi dikurangi retur',
      reasons: [],
      actions: [],
    },
    {
      id: 839,
      reconciliation_id: 127,
      stock_category: 6,
      smile_qty: 0,
      real_qty: 0,
      stock_category_label: 'Pembuangan',
      reasons: [],
      actions: [],
    },
    {
      id: 840,
      reconciliation_id: 127,
      stock_category: 7,
      smile_qty: 0,
      real_qty: 1,
      stock_category_label: 'Sisa stock',
      reasons: [
        {
          id: 1,
          title: 'Tidak ada di SMILE',
        },
        {
          id: 2,
          title: 'Belum diupdate',
        },
      ],
      actions: [
        {
          id: 1,
          title: 'Laporkan Kejadian',
        },
        {
          id: 1,
          title: 'Laporkan Kejadian',
        },
      ],
    },
  ],
}
