services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management-alpine
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit frame_max 1048576
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./logs:/var/log/rabbitmq/log
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    restart: always
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
      - apparmor:unconfined
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
