services:
  minio:
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2024-09-22T00-33-43Z
    restart: always
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - ./data/files:/data
    env_file:
      - .env
    command: minio server /data --console-address ":9001"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
      - apparmor:unconfined
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s