export enum WorkingStatusEnum {
  NEED_REPAIR = 9,
  UNSUBSCRIBED = 8,
  NOT_USED = 7,
  DEFROSTING = 6,
  UNREPAIRABLE = 5,
  DAMAGED = 4,
  REPAIR = 3,
  STANDBY = 2,
  FUNCTION = 1,
}

export enum TEMP_LOGGER {
  NORMAL = 1,
  ABOVE_MAX = 2,
  BELOW_MIN = 3,
}

export enum ASSET_TYPE {
  VACCINE_REFRIGERATOR = 1,
  FREEZER = 2,
  COLD_ROOM = 3,
  FREEZER_ROOM = 4,
  REMOTE_TEMPERATURE_MONITORING = 7,
  ULTRA_LOW_TEMPERATURE = 12,
  VACCINE_CARRIER = 14,
  CONTINUE_TEMPERATURE_MONITORING = 16,
  FREEZE_INDICATOR = 17,
}

export enum MONITORING_DEVICE_INVENTORY_STATUS {
  INACTIVE = 0,
  ACTIVE = 1,
}
