export const ENTITY_TYPE = {
  PROVINSI: 1,
  KOTA: 2,
  FASKES: 3,
  PUSAT: 5,
}

export const ENTITY_TAG = {
  MAIN_SUPPLIER: 1,
  MINISTRY_OF_HEALTH: 3,
  PROVINCE_HEALTH_OFFICE: 5,
  CITY_DISTRICT_HEALTH_OFFICE: 7,
  COMMUNITY_HEALTH_CENTER: 9,
  HOSPITAL: 11,
}
