export const TRANSACTION_TYPE = {
  STOCK_COUNT: 1,
  ISSUES: 2,
  RECEIPTS: 3,
  DISCARDS: 4,
  RETURN: 5,
  RECEIPT_OPEN_VIAL: 6,
  ADD_STOCK: 7,
  REMOVE_STOCK: 8,
  CANCEL_DISCARD: 9,
  CONSUMPTION: 10,
  TRANSFER_STOCK: 11,
}

export const MAP_TRANSACTION_TYPE_LABEL = {
  [TRANSACTION_TYPE.STOCK_COUNT]: "stockcount",
  [TRANSACTION_TYPE.ADD_STOCK]: "addremove",
}

export const MAP_MATERIAL_CONDITION_TYPE = {
  stockcount: TRANSACTION_TYPE.STOCK_COUNT,
  addremove: TRANSACTION_TYPE.ADD_STOCK,
}

export const TRANSACTION_CHANGE_TYPE = {
  ADD: 1,
  RESTOCK: 2,
  REMOVE: 3,
  TRANSFER: 4,
}
