/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface BpomLogs {
  created_at: Date;
  customer_id: Generated<number | null>;
  entity_id: Generated<number | null>;
  id: Generated<number>;
  order_id: Generated<number | null>;
  payload: Generated<string | null>;
  response: Generated<string | null>;
  response_code: Generated<string | null>;
  transaction_id: Generated<number | null>;
  transaction_type_id: Generated<number | null>;
  updated_at: Date;
  url: Generated<string | null>;
  vendor_id: Generated<number | null>;
}

export interface CovidLogs {
  created_at: Date;
  id: Generated<number>;
  order_id: Generated<number | null>;
  payload: Generated<string | null>;
  res_body: Generated<string | null>;
  res_status: Generated<number | null>;
  updated_at: Date;
  url: Generated<string | null>;
  worker_name: Generated<string | null>;
}

export interface FcmLogs {
  created_at: Date;
  id: Generated<number>;
  method: Generated<string | null>;
  request_body: Generated<string | null>;
  response_body: Generated<string | null>;
  response_status_code: Generated<number | null>;
  response_status_text: Generated<string | null>;
  updated_at: Date;
  url: Generated<string | null>;
  worker_name: Generated<string | null>;
}

export interface HttpLogs {
  created_at: Date;
  id: Generated<number>;
  method: Generated<string | null>;
  payload: Generated<string | null>;
  res_body: Generated<string | null>;
  res_status: Generated<number | null>;
  retry_status: Generated<string | null>;
  updated_at: Date;
  url: Generated<string | null>;
  worker_name: Generated<string | null>;
}

export interface Notifications {
  action_url: Generated<string | null>;
  created_at: Date;
  download_url: Generated<string | null>;
  entity_id: number;
  id: Generated<number>;
  media: string;
  message: Generated<string | null>;
  mobile_phone: Generated<string | null>;
  patient_id: Generated<number | null>;
  program_id: Generated<number | null>;
  province_id: Generated<number | null>;
  read_at: Generated<Date | null>;
  regency_id: Generated<number | null>;
  title: Generated<string | null>;
  type: string;
  updated_at: Date;
  user_id: number;
  event_code: Generated<string | null>;
}

export interface SequelizeMeta {
  name: string;
}

export interface WhatsappLogs {
  created_at: Date;
  id: Generated<number>;
  method: Generated<string | null>;
  request_body: Generated<string | null>;
  response_body: Generated<string | null>;
  response_status_code: Generated<number | null>;
  response_status_text: Generated<string | null>;
  updated_at: Date;
  url: Generated<string | null>;
  worker_name: Generated<string | null>;
}

export interface DB {
  bpom_logs: BpomLogs;
  covid_logs: CovidLogs;
  fcm_logs: FcmLogs;
  http_logs: HttpLogs;
  notifications: Notifications;
  SequelizeMeta: SequelizeMeta;
  whatsapp_logs: WhatsappLogs;
}
