export type TicketingSystem =
  | 'ticketing-system-view'
  | 'ticketing-system-create'
  | 'ticketing-system-location-filter'
  | 'ticketing-system-access-packing-link'
  | 'ticketing-system-vccm-check'
  | 'ticketing-system-report-canceled'
  | 'ticketing-system-biofarma-report-submitted'
  | 'ticketing-system-hit-manually'
  | 'ticketing-system-biofarma-review'
  | 'ticketing-system-revised'
  | 'ticketing-system-check-revision'
  | 'ticketing-system-complete'
  | 'ticketing-system-province-report'
  | 'ticketing-system-pfizer-report'
