/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = ColumnType<JsonValue, string, string>;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface BpomLogs {
  created_at: Date;
  customer_id: number | null;
  entity_id: number | null;
  id: Generated<number>;
  order_id: number | null;
  payload: string | null;
  response: string | null;
  response_code: string | null;
  transaction_id: number | null;
  transaction_type_id: number | null;
  updated_at: Date;
  url: string | null;
  vendor_id: number | null;
}

export interface CovidLogs {
  created_at: Date;
  id: Generated<number>;
  order_id: number | null;
  payload: string | null;
  res_body: string | null;
  res_status: number | null;
  updated_at: Date;
  url: string | null;
  worker_name: string | null;
}

export interface FcmLogs {
  created_at: Date;
  id: Generated<number>;
  method: string | null;
  request_body: string | null;
  response_body: string | null;
  response_status_code: number | null;
  response_status_text: string | null;
  updated_at: Date;
  url: string | null;
  worker_name: string | null;
}

export interface HttpLogs {
  created_at: Date;
  id: Generated<number>;
  method: string | null;
  payload: string | null;
  res_body: string | null;
  res_status: number | null;
  retry_status: string | null;
  updated_at: Date;
  url: string | null;
  worker_name: string | null;
}

export interface Notifications {
  action_url: string | null;
  created_at: Date;
  data: Json | null;
  download_url: string | null;
  entity_id: number;
  event_code: string | null;
  id: Generated<number>;
  media: string;
  message: string | null;
  mobile_phone: string | null;
  patient_id: number | null;
  program_id: number | null;
  protocol_id: number | null;
  province_id: number | null;
  read_at: Date | null;
  regency_id: number | null;
  title: string | null;
  type: string;
  updated_at: Date;
  user_id: number;
}

export interface SequelizeMeta {
  name: string;
}

export interface DB {
  bpom_logs: BpomLogs;
  covid_logs: CovidLogs;
  fcm_logs: FcmLogs;
  http_logs: HttpLogs;
  notifications: Notifications;
  SequelizeMeta: SequelizeMeta;
}
