import { Router } from 'express';
import { setAuthController } from '../controllers/authController';
// import { translationMiddleware } from '../middlewares/translationMiddleware';
import wasteRoutes from './wasteRoutes';
import assetManufacturer from './assetManufacturerRoutes';
import assetModel from './assetModelRoutes';
import healthcareFacilityAsset from './healthcareFacilityAssetRoutes';
import wasteSourceRoutes from './wasteSourceRoutes';
import partnershipRoutes from './partnershipRoutes';
import partnershipOperatorMapRoutes from './partnershipOperatorMapRoutes';
import wasteHierarchyRouters from './wasteHierarchyRouters';
import wasteClassificationRoutes from './wasteClassificationRoutes';
import qrCodeConfigRoutes from './qrCodeConfigRoutes';
import regionRoutes from './regionRoutes';
import parnerVehicleRoutes from './partnerVehicleRoutes';
import wasteBagQrCodeRoutes from './wasteBageQrCodeRoutes';
import wasteTransportationGroupRoutes from './wasteTransportationGroupRoutes';
import wasteTransportationRequestRoutes from './wasteTransportationRequestRoutes';
import wasteBagTreatmentRequestRoutes from './wasteBagTreatmentRequestRoutes';
import partnershipVehicleMapRoutes from './partnershipVehicleMapRoutes';
import healthcareFacitlityAssetActivityRoutes from './healthcareFacilityAssetActivityRoutes';
import enititySettings from './enititySettingsRoutes';
import entityLocation from './entityLocationRoutes';
import globalSettings from './globalSettingsRoutes';
import userRoleRoutes from './userRoleRouters';
import wasteBagAuditTrailRoutes from './wasteBagAuditTrailRoutes';
import manualScaleRequest from './manualScaleRequest';
import wasteBagTreatmentGroup from './wasteBagTreatmentGroupRoutes';
import wasteTreatmentExternalGroupRoutes from './wasteTreatmentExternalGroupRoutes';
import wasteTransportExternalGroupRoutes from './wasteTransportExternalGroupRoutes';
import dashboardRoutes from './dashboardRoutes';
import notificationRoutes from './notificationRoutes';
import userFcmTokenRoutes from './userFcmTokenRoutes';
import disposalRoutes from './disposalRoutes';
import entitiesRoutes from './entitiesRoutes';
import wasteRecordRouter from './wasteRecordRouter';
import wasteBagMonitoringDashboardRoutes from './wasteBagMonitoringDashboardRoutes';
import healthcareAssetRoutes from './healthcareAssetRoutes';
import usersRoutes from './usersRoutes';
import assetDongle from './assetDongleRoutes';
import speedRoutes from './speedRoutes';

export const v1Router = Router();

// v1Router.use(translationMiddleware);

v1Router.get('/set-auth', setAuthController);

v1Router.use('/region', regionRoutes);
v1Router.use('/waste', wasteRoutes);
v1Router.use('/asset', assetManufacturer);
v1Router.use('/asset-model', assetModel);
v1Router.use('/healthcare-facility-asset', healthcareFacilityAsset);
v1Router.use('/waste-source', wasteSourceRoutes);
v1Router.use('/partnership', partnershipRoutes);
v1Router.use('/partnership-operator-map', partnershipOperatorMapRoutes);
v1Router.use('/partnership-vehicle-map', partnershipVehicleMapRoutes);
v1Router.use('/waste-hierarchy', wasteHierarchyRouters);
v1Router.use('/waste-classification', wasteClassificationRoutes);
v1Router.use('/qr-code-config', qrCodeConfigRoutes);
v1Router.use('/partner-vehicle', parnerVehicleRoutes);
v1Router.use('/waste-bag-qrcode', wasteBagQrCodeRoutes);
v1Router.use('/waste-transportation-group', wasteTransportationGroupRoutes);
v1Router.use('/waste-transportation-request', wasteTransportationRequestRoutes);
v1Router.use('/waste-bag-treatment-group', wasteBagTreatmentGroup);
v1Router.use('/waste-bag-treatment-request', wasteBagTreatmentRequestRoutes);
v1Router.use('/healthcare-facility-asset-activity', healthcareFacitlityAssetActivityRoutes);
v1Router.use('/entity-settings', enititySettings);
v1Router.use('/entity-location', entityLocation);
v1Router.use('/global-settings', globalSettings);
v1Router.use('/roles', userRoleRoutes);
v1Router.use('/audit-trail', wasteBagAuditTrailRoutes);
v1Router.use('/manual-scale', manualScaleRequest);
v1Router.use('/waste-treatment-external-group', wasteTreatmentExternalGroupRoutes);
v1Router.use('/waste-transport-external-group', wasteTransportExternalGroupRoutes);
v1Router.use('/dashboard', dashboardRoutes);
v1Router.use('/notification', notificationRoutes);
v1Router.use('/fcm-token', userFcmTokenRoutes);
v1Router.use('/bast', disposalRoutes);
v1Router.use('/entities', entitiesRoutes);
v1Router.use('/dashboard-monitoring', wasteBagMonitoringDashboardRoutes);
v1Router.use('/waste-record', wasteRecordRouter);
v1Router.use('/healthcare-asset', healthcareAssetRoutes);
v1Router.use('/users', usersRoutes);
v1Router.use('/asset-dongle', assetDongle);
v1Router.use('/speed', speedRoutes);
