export default class Entities {
  public id?: number;
  public name?: string;
  public type?: number;
  public address?: string;
  public tag?: string;
  public province_id?: string;
  public regency_id?: string;
  public sub_district_id?: string;
  public village_id?: string;
  public integration_type?: number;
  public integration_client_id?: number;
  public location?: string;
  public external_properties?: object;
  public entity_type_id?: number;
  public entity_type_name?: string;
  public entity_type_integration_type?: number;
  public entity_type_external_properties?: string;
  public province_name?: string;
  public regency_name?: string;
  public district_name?: string;
  public updated_at?: Date;
  public code?: string;
  public nib?: string;
  public head_name?: string;
  public email?: string;
  public gender?: number;
  public mobile_phone?: string;
  public latitude?: number;
  public longitude?: number;
  public id_satu_sehat?: number;
  public total_bad_room?: number;
  public percentage_bad_room?: number;
  public is_active?: boolean;
  public count_dongle?: number;

  constructor(data: {
    id?: number;
    name?: string;
    type?: number;
    address?: string;
    tag?: string;
    province_id?: string;
    regency_id?: string;
    sub_district_id?: string;
    village_id?: string;
    integration_type?: number;
    integration_client_id?: number;
    location?: string;
    external_properties?: object;
    entity_type_id?: number;
    entity_type_name?: string;
    entity_type_integration_type?: number;
    entity_type_external_properties?: string;
    province_name?: string;
    regency_name?: string;
    district_name?: string;
    updated_at?: Date;
    code?: string;
    nib?: string;
    head_name?: string;
    email?: string;
    gender?: number;
    mobile_phone?: string;
    latitude?: number;
    longitude?: number;
    id_satu_sehat?: number;
    total_bad_room?: number;
    percentage_bad_room?: number;
    is_active?: boolean;
    count_dongle?: number;
  }) {
    this.id = data.id;
    this.name = data.name;
    this.type = data.type;
    this.address = data.address;
    this.tag = data.tag;
    this.province_id = data.province_id;
    this.regency_id = data.regency_id;
    this.sub_district_id = data.sub_district_id;
    this.village_id = data.village_id;
    this.integration_type = data.integration_type;
    this.integration_client_id = data.integration_client_id;
    this.location = data.location;
    this.external_properties = data.external_properties;
    this.entity_type_id = data.entity_type_id;
    this.entity_type_name = data.entity_type_name;
    this.entity_type_integration_type = data.entity_type_integration_type;
    this.province_name = data.province_name;
    this.regency_name = data.regency_name;
    this.district_name = data.district_name;
    this.updated_at = data.updated_at;
    this.code = data.code;
    this.nib = data.nib;
    this.head_name = data.head_name;
    this.email = data.email;
    this.gender = data.gender;
    this.mobile_phone = data.mobile_phone;
    this.latitude = data.latitude;
    this.longitude = data.longitude;
    this.id_satu_sehat = data.id_satu_sehat;
    this.total_bad_room = data.total_bad_room;
    this.percentage_bad_room = data.percentage_bad_room;
    this.is_active = data.is_active;
    this.count_dongle = data.count_dongle;
  }
}
