export default class Notification {
    public id?: number;
    public message?: string;
    public userId: number;
    public provinceId?: number;
    public regencyId?: number;
    public entityId: number;
    public media: string;
    public title?: string;
    public type: string;
    public createdAt?: Date;
    public updatedAt?: Date;
    public readAt?: Date | null;
    public mobilePhone?: string;
    public actionUrl?: string;
    public downloadUrl?: string;
    public patientId?: number | null;
    public programId?: number | null;
    public userName?: string;
    public entityName?: string;
    public forSuperAdmin?: boolean;
    public forAdmin?: boolean;
    public forOperator?: boolean;

    constructor(data: {
        id?: number;
        message?: string;
        userId: number;
        provinceId?: number;
        regencyId?: number;
        entityId: number;
        media: string;
        title?: string;
        type: string;
        createdAt?: Date;
        updatedAt?: Date;
        readAt?: Date | null;
        mobilePhone?: string;
        actionUrl?: string;
        downloadUrl?: string;
        patientId?: number | null;
        programId?: number | null;
        userName?: string;
        entityName?: string;
        forSuperAdmin?: boolean;
        forAdmin?: boolean;
        forOperator?: boolean;
    }) {
        this.id = data.id;
        this.message = data.message;
        this.userId = data.userId;
        this.provinceId = data.provinceId;
        this.regencyId = data.regencyId;
        this.entityId = data.entityId;
        this.media = data.media;
        this.title = data.title;
        this.type = data.type;
        this.createdAt = data.createdAt;
        this.updatedAt = data.updatedAt;
        this.readAt = data.readAt;
        this.mobilePhone = data.mobilePhone;
        this.actionUrl = data.actionUrl;
        this.downloadUrl = data.downloadUrl;
        this.patientId = data.patientId;
        this.programId = data.programId;
        this.userName = data.userName;
        this.entityName = data.entityName;
        this.forSuperAdmin = data.forSuperAdmin;
        this.forAdmin = data.forAdmin;
        this.forOperator = data.forOperator;
    }
}
