export default class Users {
    public id?: number;
    public user_uuid!: string;
    public entity_id!: number;
    public firstname?: string;
    public lastname?: string;
    public email?: string;
    public username?: string;
    public mobile_phone?: string;
    public gender?: number;
    public gender_label?: string;
    public date_of_birth?: string;
    public role?: number;
    public role_id?: number;
    public role_label?: string;
    public view_only?: boolean;
    public status?: number;
    public last_device?: number;
    public last_login?: string;
    public integration_client_id?: number;
    public keycloak_uuid?: string;
    public external_roles?: string;
    public address?: string;
    public manufacture_id?: number;
    public village_id?: string;
    public external_properties?: object;
    public deleted_at?: string;
    public created_at?: string;
    public updated_at?: string;
    public created_by?: number;
    public updated_by?: number;
    public deleted_by?: number;
    public is_active?: boolean;

    constructor(data: {
        id?: number;
        user_uuid: string;
        entity_id: number;
        firstname?: string;
        lastname?: string;
        email?: string;
        username?: string;
        mobile_phone?: string;
        gender?: number;
        gender_label?: string;
        date_of_birth?: string;
        role?: number;
        role_id?: number;
        role_label?: string;
        view_only?: boolean;
        status?: number;
        last_device?: number;
        last_login?: string;
        integration_client_id?: number;
        keycloak_uuid?: string;
        external_roles?: string;
        address?: string;
        manufacture_id?: number;
        village_id?: string;
        external_properties?: object;
        deleted_at?: string;
        created_at?: string;
        updated_at?: string;
        created_by?: number;
        updated_by?: number;
        deleted_by?: number;
        is_active?: boolean;
    }) {
        this.id = data.id;
        this.user_uuid = data.user_uuid;
        this.entity_id = data.entity_id;
        this.firstname = data.firstname;
        this.lastname = data.lastname;
        this.email = data.email;
        this.username = data.username;
        this.mobile_phone = data.mobile_phone;
        this.gender = data.gender;
        this.gender_label = data.gender_label;
        this.date_of_birth = data.date_of_birth;
        this.role = data.role;
        this.role_id = data.role_id;
        this.role_label = data.role_label;
        this.view_only = data.view_only;
        this.status = data.status;
        this.last_device = data.last_device;
        this.last_login = data.last_login;
        this.integration_client_id = data.integration_client_id;
        this.keycloak_uuid = data.keycloak_uuid;
        this.external_roles = data.external_roles;
        this.address = data.address;
        this.manufacture_id = data.manufacture_id;
        this.village_id = data.village_id;
        this.external_properties = data.external_properties;
        this.deleted_at = data.deleted_at;
        this.created_at = data.created_at;
        this.updated_at = data.updated_at;
        this.created_by = data.created_by;
        this.updated_by = data.updated_by;
        this.deleted_by = data.deleted_by;
        this.is_active = data.is_active;
    }
}
