import { WasteHierarchyAttributes } from '../../infrastructure/database/models/WasteHierarchyModel';
export default class WasteClassification {
    public id: number | undefined;
    public createdAt: Date;
    public createdBy: string;
    public updatedAt: Date | undefined;
    public updatedBy: string | undefined;
    public regionId: number;
    public effectiveFrom: Date;
    public effectiveTo: Date;
    public wasteTypeId: number;
    public wasteGroupId: number;
    public wasteCharacteristicsId: number;
    public wasteCode: string;
    public wasteBagColorCode: 'BLACK' | 'GRAY' | 'YELLOW' | 'PURPLE' | 'BROWN' | 'RED' | 'NONE';
    public storageRuleType: 'STATIC' | 'RULE_BASED' | undefined;
    public useColdStorage: boolean;
    public coldStorageMinHours: number | undefined;
    public coldStorageMaxHours: number | undefined;
    public tempStorageMinHours: number | undefined;
    public tempStorageMaxHours: number | undefined;
    public minimunDecayDay: number | undefined;
    public storageRule: string | undefined;
    public allowHealthcareFacilityTreatment: boolean;
    public isActive: boolean;
    public hasMultipleTransporters: boolean;
    public treatmentMethod?: string | null;
    public disposalMethod: string | undefined;
    public allowedVehicleTypes?: string | null;
    public readonly wasteType?: WasteHierarchyAttributes;
    public readonly wasteGroup?: WasteHierarchyAttributes;
    public readonly wasteCharacteristics?: WasteHierarchyAttributes;
    public userName?: string;
    public createdByName?: string;

    constructor(data: {
        id?: number;
        createdAt: Date;
        createdBy: string;
        updatedAt?: Date;
        updatedBy?: string;
        regionId: number;
        effectiveFrom: Date;
        effectiveTo: Date;
        wasteTypeId: number;
        wasteGroupId: number;
        wasteCharacteristicsId: number;
        wasteCode: string;
        wasteBagColorCode: 'BLACK' | 'GRAY' | 'YELLOW' | 'PURPLE' | 'BROWN' | 'RED' | 'NONE';
        storageRuleType: 'STATIC' | 'RULE_BASED' | undefined;
        useColdStorage: boolean;
        coldStorageMinHours: number | undefined;
        coldStorageMaxHours: number | undefined;
        tempStorageMinHours: number | undefined;
        tempStorageMaxHours: number | undefined;
        minimunDecayDay: number | undefined;
        storageRule: string | undefined;
        allowHealthcareFacilityTreatment: boolean;
        isActive: boolean;
        hasMultipleTransporters: boolean;
        treatmentMethod?: string | null;
        disposalMethod: string | undefined;
        allowedVehicleTypes?: string | null;
        wasteType?: WasteHierarchyAttributes;
        wasteGroup?: WasteHierarchyAttributes;
        wasteCharacteristics?: WasteHierarchyAttributes;
        userName?: string;
        createdByName?: string;
    }) {
        this.id = data.id ?? undefined;
        this.createdAt = data.createdAt;
        this.createdBy = data.createdBy;
        this.updatedAt = data.updatedAt ?? undefined;
        this.updatedBy = data.updatedBy;
        this.regionId = data.regionId;
        this.effectiveFrom = data.effectiveFrom;
        this.effectiveTo = data.effectiveTo;
        this.wasteTypeId = data.wasteTypeId;
        this.wasteGroupId = data.wasteGroupId;
        this.wasteCharacteristicsId = data.wasteCharacteristicsId;
        this.wasteCode = data.wasteCode;
        this.wasteBagColorCode = data.wasteBagColorCode;
        this.storageRuleType = data.storageRuleType ?? undefined;
        this.useColdStorage = data.useColdStorage;
        this.coldStorageMinHours = data.coldStorageMinHours ?? undefined;
        this.coldStorageMaxHours = data.coldStorageMaxHours ?? undefined;
        this.tempStorageMinHours = data.tempStorageMinHours ?? undefined;
        this.tempStorageMaxHours = data.tempStorageMaxHours ?? undefined;
        this.minimunDecayDay = data.minimunDecayDay ?? undefined;
        this.storageRule = data.storageRule ?? undefined;
        this.allowHealthcareFacilityTreatment = data.allowHealthcareFacilityTreatment;
        this.isActive = data.isActive;
        this.hasMultipleTransporters = data.hasMultipleTransporters;
        this.treatmentMethod = data.treatmentMethod ?? null;
        this.disposalMethod = data.disposalMethod;
        this.allowedVehicleTypes = data.allowedVehicleTypes ?? null;
        this.wasteType = data.wasteType;
        this.wasteGroup = data.wasteGroup;
        this.wasteCharacteristics = data.wasteCharacteristics;
        this.userName = data.userName;
        this.createdByName = data.createdByName;
    }
}
