import { MapName } from '#components/chart'

export const MAP_CODE_TO_SLUG: Record<string, MapName> = {
  'INDONESIA': 'indonesia',
  '11_PROV. ACEH': 'aceh',
  '12_PROV. SUMATERA UTARA': 'north-sumatera',
  '13_PROV. SUMATERA BARAT': 'west-sumatera',
  '14_PROV. RIAU': 'riau',
  '15_PROV. JAMBI': 'jambi',
  '16_PROV. SUMATERA SELATAN': 'south-sumatera',
  '17_PROV. BENGKULU': 'bengkulu',
  '18_PROV. LAMPUNG': 'lampung',
  '19_PROV. KEPULAUAN BANGKA BELITUNG': 'bangka-belitung-island',
  '21_PROV. KEPULAUAN RIAU': 'riau-island',
  '31_PROV. DKI JAKARTA': 'jakarta',
  '32_PROV. JAWA BARAT': 'west-java',
  '33_PROV. JAWA TENGAH': 'central-java',
  '34_PROV. DI YOGYAKARTA': 'yogyakarta',
  '35_PROV. JAWA TIMUR': 'east-java',
  '36_PROV. BANTEN': 'banten',
  '51_PROV. BALI': 'bali',
  '52_PROV. NUSA TENGGARA BARAT': 'west-nusa-tenggara',
  '53_PROV. NUSA TENGGARA TIMUR': 'east-nusa-tenggara',
  '61_PROV. KALIMANTAN BARAT': 'west-kalimantan',
  '62_PROV. KALIMANTAN TENGAH': 'central-kalimantan',
  '63_PROV. KALIMANTAN SELATAN': 'south-kalimantan',
  '64_PROV. KALIMANTAN TIMUR': 'east-kalimantan',
  '65_PROV. KALIMANTAN UTARA': 'north-kalimantan',
  '71_PROV. SULAWESI UTARA': 'north-sulawesi',
  '72_PROV. SULAWESI TENGAH': 'central-sulawesi',
  '73_PROV. SULAWESI SELATAN': 'south-sulawesi',
  '74_PROV. SULAWESI TENGGARA': 'southeast-sulawesi',
  '75_PROV. GORONTALO': 'gorontalo',
  '76_PROV. SULAWESI BARAT': 'west-sulawesi',
  '81_PROV. MALUKU': 'maluku',
  '82_PROV. MALUKU UTARA': 'north-maluku',
  '91_PROV. PAPUA': 'papua',
  '92_PROV. PAPUA BARAT': 'west-papua',
  '93_PROV. PAPUA SELATAN': 'south-papua',
  '94_PROV. PAPUA TENGAH': 'central-papua',
  '95_PROV. PAPUA PEGUNUNGAN': 'highland-papua',
  '96_PROV. PAPUA BARAT DAYA': 'southwest-papua',
}
