export enum TRANSACTION_TYPE_TYPE {
  STOCK_COUNT = 1,
  ISSUE = 2,
  RECEIVE = 3,
  DISCARD = 4,
  RETURN_OF_HEALTH_FACILITIES = 5,
  OPEN_VIAL_ACCEPTANCE = 6,
  ADD_STOCK = 7,
  REDUCE_STOCK = 8,
  CANCELLATION_OF_DISCARD = 9,
  CONSUMPTION = 10,
}