CREATE TABLE waste_hierarchy (
    id SERIAL PRIMARY KEY,
    created_by TEXT NOT NULL,
    updated_by TEXT NOT NULL,
    region_id INTEGER NOT NULL REFERENCES regions (id),
    parent_hierarchy_id INTEGER REFERENCES waste_hierarchy (id),
    name TEXT NOT NULL,
    name_en TEXT NOT NULL,
    description TEXT,
    description_en TEXT,
    level INTEGER NOT NULL DEFAULT 0,
    is_residue BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    deleted_by INTEGER
);

CREATE TYPE waste_bag_color_code AS ENUM ('BLACK', 'GRAY', 'YELLOW', 'PURPLE', 'BROWN', 'RED', 'NONE');
CREATE TYPE storage_rule_type AS ENUM ('STATIC', 'RULE_BASED');

CREATE TABLE waste_classification (
    id SERIAL PRIMARY KEY,
    created_by TEXT NOT NULL,
    updated_by TEXT NOT NULL,
    region_id INTEGER NOT NULL REFERENCES regions (id),
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ NOT NULL,
    waste_type_id INTEGER NOT NULL REFERENCES waste_hierarchy (id),
    waste_group_id INTEGER NOT NULL REFERENCES waste_hierarchy (id),
    waste_characteristics_id INTEGER NOT NULL REFERENCES waste_hierarchy (id),
    waste_code TEXT NOT NULL,
    waste_bag_color_code waste_bag_color_code NOT NULL,
    storage_rule_type storage_rule_type,
    use_cold_storage BOOLEAN NOT NULL DEFAULT false,
    cold_storage_min_hours INTEGER,
    cold_storage_max_hours INTEGER,
    temp_storage_min_hours INTEGER,
    temp_storage_max_hours INTEGER,
    minimun_decay_day INTEGER,
    storage_rule JSONB,
    allow_healthcare_facility_treatment BOOLEAN NOT NULL DEFAULT true,
    is_active BOOLEAN NOT NULL DEFAULT true,
    has_multiple_transporters BOOLEAN NOT NULL DEFAULT false,
    treatment_method TEXT,
    disposal_method TEXT,
    allowed_vehicle_types TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    deleted_by INTEGER
);

CREATE TYPE waste_source_type AS ENUM ('INTERNAL', 'EXTERNAL', 'INTERNAL_TREATMENT');
CREATE TYPE internal_treatment_name AS ENUM ('PYROLYSIS', 'DISINFECTION');

CREATE TABLE waste_source (
    id SERIAL PRIMARY KEY,
    created_by TEXT NOT NULL,
    updated_by TEXT NOT NULL,
    healthcare_facility_id INTEGER NOT NULL,
    source_type waste_source_type NOT NULL DEFAULT 'INTERNAL',
    internal_source_name TEXT,
    internal_treatment_name internal_treatment_name,
    external_healthcare_facility_id INTEGER,
    external_healthcare_facility_name TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    is_residue BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    deleted_by INTEGER
);

-- Enum-like columns (waste_status, scale_method, transportation_status,
-- owned_by, iot_method) are plain TEXT — see db.ts's WasteBagTable comment
-- for why (validated at the Zod/service layer instead of the DB layer here).
-- waste_treatment_group_id / waste_transportation_group_id / *_external_*
-- have no FK constraint yet — those tables don't exist (Batch B, still to
-- come in this same migration pass).
CREATE TABLE waste_bag (
    id SERIAL PRIMARY KEY,
    created_by TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    updated_by TEXT,
    waste_bag_qr_code_id TEXT NOT NULL UNIQUE,
    healthcare_facility_id INTEGER NOT NULL,
    waste_source_id INTEGER NOT NULL REFERENCES waste_source (id),
    waste_classification_id INTEGER NOT NULL REFERENCES waste_classification (id),
    source_treatment_group_id TEXT,
    scale_method TEXT NOT NULL DEFAULT 'IOT',
    asset_id INTEGER,
    weight_in_kgs NUMERIC(10, 2),
    storage_start_timestamp TIMESTAMPTZ,
    scheduled_storage_end_datetime TIMESTAMPTZ,
    actual_storage_end_timestamp TIMESTAMPTZ,
    max_storage_hours INTEGER,
    min_storage_hours INTEGER,
    waste_treatment_group_id INTEGER,
    waste_transportation_group_id INTEGER,
    waste_treatment_external_group_id INTEGER,
    waste_transportation_external_group_id INTEGER,
    waste_status TEXT NOT NULL DEFAULT 'IN_TEMPORARY_STORAGE',
    waste_status_updated_at TIMESTAMPTZ DEFAULT now(),
    waste_status_updated_by TEXT,
    transportation_status TEXT,
    transportation_status_updated_at TIMESTAMPTZ DEFAULT now(),
    transportation_status_updated_by TEXT,
    owned_by TEXT NOT NULL DEFAULT 'HEALTHCARE_FACILITY',
    transporter_id INTEGER,
    third_party_id INTEGER,
    is_treated BOOLEAN NOT NULL DEFAULT false,
    is_disposed BOOLEAN NOT NULL DEFAULT false,
    bin_number TEXT,
    iot_method TEXT,
    manifest_doc_number TEXT,
    manifest_doc_path TEXT,
    treatment_start_time TIMESTAMPTZ,
    treatment_end_time TIMESTAMPTZ,
    waste_group_ids TEXT,
    treatment_location_id INTEGER,
    healthcare_facility_name TEXT,
    province_id INTEGER,
    province_name TEXT,
    regency_id INTEGER,
    regency_name TEXT,
    district_id INTEGER,
    district_name TEXT,
    transporter_name TEXT,
    third_party_name TEXT,
    bast_no TEXT,
    material_ids TEXT,
    deleted_at TIMESTAMPTZ,
    deleted_by INTEGER
);

-- TEXT, not BIGINT — every real value written is a zero-padded numeric
-- string; the model's declared type doesn't match actual usage, same
-- situation as asset_dongle.asset_id (see db.ts's comment).
CREATE TABLE waste_bag_qr_code (
    id SERIAL PRIMARY KEY,
    created_by TEXT NOT NULL,
    healthcare_facility_id INTEGER,
    waste_classification_id INTEGER REFERENCES waste_classification (id),
    waste_source_id INTEGER REFERENCES waste_source (id),
    qr_code TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    deleted_by INTEGER
);

-- Near-duplicate of waste_bag — a historical/snapshot record.
CREATE TABLE waste_bag_record (
    id SERIAL PRIMARY KEY,
    created_by TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    updated_by TEXT,
    waste_bag_qr_code_id TEXT NOT NULL UNIQUE,
    healthcare_facility_id INTEGER NOT NULL,
    waste_source_id INTEGER NOT NULL REFERENCES waste_source (id),
    waste_classification_id INTEGER NOT NULL REFERENCES waste_classification (id),
    source_treatment_group_id TEXT,
    scale_method TEXT NOT NULL DEFAULT 'IOT',
    asset_id INTEGER,
    weight_in_kgs NUMERIC(10, 2),
    storage_start_timestamp TIMESTAMPTZ,
    scheduled_storage_end_datetime TIMESTAMPTZ,
    actual_storage_end_timestamp TIMESTAMPTZ,
    max_storage_hours INTEGER,
    min_storage_hours INTEGER,
    waste_treatment_group_id INTEGER,
    waste_transportation_group_id INTEGER,
    waste_treatment_external_group_id INTEGER,
    waste_transportation_external_group_id INTEGER,
    waste_status TEXT NOT NULL DEFAULT 'IN_TEMPORARY_STORAGE',
    waste_status_updated_at TIMESTAMPTZ DEFAULT now(),
    waste_status_updated_by TEXT,
    transportation_status TEXT,
    transportation_status_updated_at TIMESTAMPTZ DEFAULT now(),
    transportation_status_updated_by TEXT,
    owned_by TEXT NOT NULL DEFAULT 'HEALTHCARE_FACILITY',
    transporter_id INTEGER,
    third_party_id INTEGER,
    is_treated BOOLEAN NOT NULL DEFAULT false,
    is_disposed BOOLEAN NOT NULL DEFAULT false,
    bin_number TEXT,
    iot_method TEXT,
    manifest_doc_number TEXT,
    manifest_doc_path TEXT,
    treatment_start_time TIMESTAMPTZ,
    treatment_end_time TIMESTAMPTZ,
    waste_group_ids TEXT,
    treatment_location_id INTEGER,
    healthcare_facility_name TEXT,
    province_id INTEGER,
    province_name TEXT,
    regency_id INTEGER,
    regency_name TEXT,
    district_id INTEGER,
    district_name TEXT,
    transporter_name TEXT,
    third_party_name TEXT,
    bast_no TEXT,
    material_ids TEXT,
    deleted_at TIMESTAMPTZ,
    deleted_by INTEGER
);
