export const ENTITY_STATUS = {
  ACTIVE: 1,
  INACTIVE: 0,
}

export const ENTITY_TYPE = {
  PROVINCE: 1,
  REGENCY: 2,
  HEALTHCARE_FACILITY: 3,
  DISTRICT_HEALTH_CENTER: 4,
  CENTER: 5,
  THIRD_PARTY: 6,
}

export const ENTITY_IS_VENDOR = {
  IS_VENDOR: 1,
  IS_NOT_VENDOR: 0,
}

export const ENTITY_TAG = {
  MAIN_SUPPLIER: 1,
  MINISTRY_OF_HEALTH: 3,
  PROVINCE_HEALTH_OFFICE: 5,
  CITY_DISTRICT_HEALTH_OFFICE: 7,
}
