export const TRANSACTION_TYPE = {
  STOCK_COUNT: 1,
  ISSUES: 2,
  RECEIVE: 3,
  DISCARDS: 4,
  RETURN: 5,
  OPENED_RECEIVES: 6,
  STOCK_ADD: 7,
  STOCK_REMOVE: 8,
  CONSUMPTION: 10,
  CANCEL_DISCARD: 11,
}

export const TRANSACTION_CHANGE_TYPE = {
  RECEIVE: 1,
  REMOVE: 2,
  ISSUE: 3,
}
