export const EXTERMINATION_ORDER_TYPE = {
  INDEPENDENT_EXTERMINATION: 4,
}

export const ORDER_STATUS = {
  INDEPENDENT_EXTERMINATION: 10,
}

export const EXTERMINATION_TRANSACTION_TYPE = {
  INDEPENDENT_EXTERMINATION: 3,
}
