import { TAssetInventoryChildData } from './detail/libs/asset-inventory-detail.types'
import { TAssetInventory } from './list/libs/asset-inventory-list.types'

export const DUMMY_GLOBAL_LIST_DATA = {
  statusCode: 200,
  page: 1,
  item_per_page: 10,
  total_item: 3,
  total_page: 1,
  list_pagination: [10, 25, 50, 100],
  data: [
    {
      id: 189,
      serial_number: 'TR11229900',
      updated_at: '2025-09-09T16:54:45.000Z',
      other_asset_model_name: null,
      other_asset_type_name: null,
      other_manufacture_name: null,
      asset_model: {
        id: 87,
        name: 'ASSET MODEL 19',
      },
      asset_type: {
        id: 92,
        name: 'ASSET TYPE 19',
      },
      manufacture: {
        id: 695,
        name: 'ADATA',
      },
      working_status: {
        id: 3,
        name: 'Dalam Perbaikan',
      },
      entity: {
        id: 10452,
        name: 'PUSKESMAS SERANG KOTA',
        is_puskesmas: 1,
      },
      province: {
        id: '36',
        name: 'PROV. BANTEN',
      },
      regency: {
        id: '3673',
        name: 'KOTA SERANG',
      },
      ownership: {
        id: 1,
        name: 'Milik Sendiri',
        qty: 20,
      },
      status: {
        id: 1,
        name: 'Aktif',
      },
      user_updated_by: {
        id: 35948,
        username: 'yogi_super',
        firstname: 'Muhammad Yogi',
        lastname: 'Mustofa',
        fullname: 'Muhammad Yogi Mustofa',
      },
      programs: [
        {
          id: 1,
          key: 'immunization',
          name: 'Imunisasi',
          entity_id: 10,
          entity_program_id: 815389,
          config: {
            material: {
              is_hierarchy_enabled: false,
              is_batch_enabled: false,
            },
            color: '#004990',
          },
        },
        {
          id: 2,
          key: 'logistic',
          name: 'OBAT ESSENSIAL',
          entity_id: 10,
          entity_program_id: 10,
          config: {
            material: {
              is_hierarchy_enabled: true,
              is_batch_enabled: false,
            },
            color: '#680771',
          },
        },
        {
          id: 3,
          key: 'malaria',
          name: 'MALARIA',
          entity_id: 10,
          entity_program_id: 825405,
          config: {
            material: {
              is_hierarchy_enabled: true,
              is_batch_enabled: false,
            },
            color: '#000000',
          },
        },
      ],
    },
    {
      id: 189,
      serial_number: '89087',
      updated_at: '2025-09-04T12:00:42.000Z',
      other_asset_model_name: null,
      other_asset_type_name: null,
      other_manufacture_name: null,
      asset_model: {
        id: 89,
        name: 'J-Model',
      },
      asset_type: {
        id: 93,
        name: 'J-Assets',
      },
      manufacture: {
        id: 727,
        name: 'PT Review Manufact',
      },
      working_status: {
        id: 1,
        name: 'Berfungsi',
      },
      entity: {
        id: 827116,
        name: 'RS ASSALAM',
        is_puskesmas: 0,
      },
      province: {
        id: '17',
        name: 'PROV. BENGKULU',
      },
      regency: {
        id: '1702',
        name: 'KAB. REJANG LEBONG',
      },
      ownership: {
        id: 1,
        name: 'Milik Sendiri',
        qty: 2,
      },
      status: {
        id: 1,
        name: 'Aktif',
      },
      user_updated_by: {
        id: 33084,
        username: 'danis_admin',
        firstname: 'Danis',
        lastname: null,
        fullname: 'Danis',
      },
      programs: [
        {
          id: 1,
          key: 'immunization',
          name: 'Imunisasi',
          entity_id: 10,
          entity_program_id: 815389,
          config: {
            material: {
              is_hierarchy_enabled: false,
              is_batch_enabled: false,
            },
            color: '#004990',
          },
        },
        {
          id: 2,
          key: 'logistic',
          name: 'OBAT ESSENSIAL',
          entity_id: 10,
          entity_program_id: 10,
          config: {
            material: {
              is_hierarchy_enabled: true,
              is_batch_enabled: false,
            },
            color: '#680771',
          },
        },
        {
          id: 3,
          key: 'malaria',
          name: 'MALARIA',
          entity_id: 10,
          entity_program_id: 825405,
          config: {
            material: {
              is_hierarchy_enabled: true,
              is_batch_enabled: false,
            },
            color: '#000000',
          },
        },
      ],
    },
    {
      id: 189,
      serial_number: 'J-Warranty-BE-NF-06-013-TC002',
      updated_at: '2025-09-04T07:48:50.000Z',
      other_asset_model_name: null,
      other_asset_type_name: null,
      other_manufacture_name: null,
      asset_model: {
        id: 89,
        name: 'J-Model',
      },
      asset_type: {
        id: 93,
        name: 'J-Assets',
      },
      manufacture: {
        id: 698,
        name: 'Landie Rover',
      },
      working_status: {
        id: 1,
        name: 'Berfungsi',
      },
      entity: {
        id: 3,
        name: 'DINKES KOTA BOGOR',
        is_puskesmas: 0,
      },
      province: {
        id: '32',
        name: 'PROV. JAWA BARAT',
      },
      regency: {
        id: '3271',
        name: 'KOTA BOGOR',
      },
      ownership: {
        id: 1,
        name: 'Milik Sendiri',
        qty: 2,
      },
      status: {
        id: 1,
        name: 'Aktif',
      },
      user_updated_by: {
        id: 31608,
        username: 'jodi_sa',
        firstname: 'Lyla',
        lastname: 'Koepp',
        fullname: 'Lyla Koepp',
      },
      programs: [
        {
          id: 1,
          key: 'immunization',
          name: 'Imunisasi',
          entity_id: 10,
          entity_program_id: 815389,
          config: {
            material: {
              is_hierarchy_enabled: false,
              is_batch_enabled: false,
            },
            color: '#004990',
          },
        },
        {
          id: 2,
          key: 'logistic',
          name: 'OBAT ESSENSIAL',
          entity_id: 10,
          entity_program_id: 10,
          config: {
            material: {
              is_hierarchy_enabled: true,
              is_batch_enabled: false,
            },
            color: '#680771',
          },
        },
        {
          id: 3,
          key: 'malaria',
          name: 'MALARIA',
          entity_id: 10,
          entity_program_id: 825405,
          config: {
            material: {
              is_hierarchy_enabled: true,
              is_batch_enabled: false,
            },
            color: '#000000',
          },
        },
      ],
    },
  ] as TAssetInventory[],
}

export const DUMMY_GLOBAL_DETAIL_DATA = {
  id: 189,
  serial_number: 'TR11229900',
  production_year: 2014,
  other_asset_model_name: null,
  other_net_capacity: null,
  other_gross_capacity: null,
  other_asset_type_name: null,
  other_min_temperature: null,
  other_max_temperature: null,
  other_manufacture_name: null,
  other_budget_source_name: null,
  other_borrowed_from_entity_name: null,
  created_at: '2025-09-09T16:49:05.000Z',
  updated_at: '2025-09-09T16:54:45.000Z',
  asset_model: {
    id: 87,
    name: 'ASSET MODEL 19',
    net_capacity: 0,
    gross_capacity: null,
  },
  asset_type: {
    id: 92,
    name: 'ASSET TYPE 19',
    min_temperature: null,
    max_temperature: null,
  },
  manufacture: {
    id: 695,
    name: 'ADATA',
  },
  working_status: {
    id: 3,
    name: 'Dalam Perbaikan',
  },
  entity: {
    id: 10452,
    name: 'PUSKESMAS SERANG KOTA',
    is_puskesmas: 1,
  },
  entity_tag: {
    id: 9,
    title: 'Puskesmas',
  },
  province: {
    id: '36',
    name: 'PROV. BANTEN',
  },
  regency: {
    id: '3673',
    name: 'KOTA SERANG',
  },
  sub_district: {
    id: '367301',
    name: 'KEC. SERANG',
  },
  village: {
    id: null,
    name: null,
  },
  contact_person: {
    first: {
      name: 'yogi',
      number: '+6289516183060',
    },
    second: {
      name: null,
      number: null,
    },
    third: {
      name: null,
      number: null,
    },
  },
  ownership: {
    id: 1,
    name: 'Milik Sendiri',
    qty: 20,
  },
  borrowed_from: {
    id: null,
    name: null,
  },
  budget_source: {
    id: 3095,
    name: 'APBN',
    year: 2014,
  },
  electricity: {
    id: 3,
    name: '12 Jam',
  },
  warranty: {
    asset_vendor_id: 91,
    asset_vendor_name: 'ASSET VENDOR 19',
    start_date: '2019-09-01T00:00:00.000Z',
    end_date: '2025-09-02T00:00:00.000Z',
  },
  calibration: {
    asset_vendor_id: 91,
    asset_vendor_name: 'ASSET VENDOR 19',
    last_date: '2023-09-01T00:00:00.000Z',
    schedule_id: 3,
    name: '6 Bulan',
  },
  maintenance: {
    asset_vendor_id: 91,
    asset_vendor_name: 'ASSET VENDOR 19',
    last_date: '2025-09-09T00:00:00.000Z',
    schedule_id: 3,
    name: '6 Bulan',
  },
  status: {
    id: 1,
    name: 'Aktif',
  },
  programs: {
    id: 2,
    key: 'logistic',
    name: 'OBAT ESSENSIAL',
    config: {
      material: {
        is_hierarchy_enabled: true,
        is_batch_enabled: false,
      },
      color: '#680771',
    },
  },
  user_created_by: {
    id: 35948,
    username: 'yogi_super',
    firstname: 'Muhammad Yogi',
    lastname: 'Mustofa',
    fullname: 'Muhammad Yogi Mustofa',
  },
  user_updated_by: {
    id: 35948,
    username: 'yogi_super',
    firstname: 'Muhammad Yogi',
    lastname: 'Mustofa',
    fullname: 'Muhammad Yogi Mustofa',
  },
} as TAssetInventory

export const DUMMY_GLOBAL_DETAIL_CHILD_DATA = {
  statusCode: 200,
  page: 1,
  item_per_page: 10,
  total_item: 3,
  total_page: 1,
  list_pagination: [10, 25, 50, 100],
  data: [
    {
      id: 13418,
      serial_number: '90378654291762808001',
      manufacture_id: 28,
      type_id: 7,
      model_id: 421,
      child_pos: 1,
      budget_year: 2000,
      budget_src: 234,
      min_temp: null,
      max_temp: null,
      min_temp_2: null,
      max_temp_2: null,
      min_temp_3: null,
      max_temp_3: null,
      other_model_asset: null,
      other_manufacture: null,
      working_status: 'Working',
      logger_status_id: 1,
      logger_status: 'Aktif',
      coldchain_capacity_equipment_id: null,
      loggers: [],
      asset_model: {
        id: 421,
        name: 'Caravell RTM 01',
        capacity: 120,
        created_at: '2023-11-30T09:35:58.000Z',
        updated_at: '2025-07-04T09:47:12.000Z',
        deleted_at: null,
        updated_by: 48213,
        created_by: 48002,
        only_logger: 0,
        capacity_gross: 150,
        capacity_nett: 120,
        capacity_gross_2: null,
        capacity_nett_2: null,
        capacity_gross_3: null,
        capacity_nett_3: null,
      },
      asset_type: {
        id: 7,
        name: 'Remote Temperature Monitoring ',
        created_at: '2021-05-07T02:50:17.000Z',
        updated_at: '2024-07-17T12:51:18.000Z',
        deleted_at: null,
        updated_by: 40900,
        created_by: 40900,
        min_temp: null,
        max_temp: null,
        min_temp_2: null,
        max_temp_2: null,
        min_temp_3: null,
        max_temp_3: null,
        is_coldstorage: 0,
        is_electricity: 0,
        description: null,
        is_selection: false,
      },
      manufacture: {
        id: 28,
        name: 'Caravell',
        reference_id: null,
        description: null,
        contact_name: null,
        phone_number: null,
        email: null,
        address: null,
        village_id: null,
        created_by: null,
        updated_by: null,
        deleted_by: null,
        type: 2,
        created_at: '2020-12-28T00:00:00.000Z',
        updated_at: '2020-12-28T00:00:00.000Z',
        deleted_at: null,
      },
      budget_source: {
        id: 234,
        name: 'Anggaran Pemilu',
      },
      parent: {
        asset_name: '9150001 -  - ()',
        id: 13417,
        serial_number: '9150001',
        prod_year: '2025',
        temp: 1,
        manufacture_id: 26,
        entity_id: 21245,
        name: null,
        type_id: 22,
        status: 1,
        lat: null,
        lng: null,
        model_id: 480,
        created_at: '2025-06-30T08:11:30.000Z',
        updated_at: '2025-09-08T04:33:40.000Z',
        deleted_at: null,
        domain_name: null,
        activity_status: null,
        activity_time: null,
        activity_duration: null,
        alarm_status: null,
        alarm_type: null,
        alarm_updated_at: null,
        alarm_duration: null,
        power_available: null,
        power_updated_at: null,
        created_by: 48213,
        updated_by: 48213,
        working_status: 'Berfungsi',
        parent_id: null,
        child_pos: null,
        budget_year: 2024,
        budget_src: 234,
        max_temp: -15,
        min_temp: -25,
        other_type_asset: null,
        other_min_temp: null,
        other_max_temp: null,
        other_model_asset: null,
        other_capacity_nett: null,
        other_capacity_gross: null,
        other_manufacture: null,
        other_budget_src: null,
        unused_reason_id: null,
        is_stock_opname: 1,
        working_status_id: 1,
        status_device: true,
        battery: 20,
        signal: 30,
        power: true,
        deleted_reason: null,
        asset_vendor_id: null,
        asset_communication_provider_id: null,
        ownership_qty: null,
        ownership_status: 1,
        borrowed_from: null,
        electricity_available_id: 1,
        logger_status_id: null,
        logger_status: null,
        coldchain_capacity_equipment_id: 17,
        warranty_start_date: null,
        warranty_end_date: null,
        maintenance_schedule_id: null,
        last_maintenance_date: null,
        calibration_schedule_id: null,
        last_calibration_date: null,
        max_temp_2: -15,
        min_temp_2: -25,
        max_temp_3: -60,
        min_temp_3: -90,
        asset_type: {
          id: 22,
          name: 'Vaccine Refrigerator&Freezer',
          created_at: '2024-03-03T10:18:11.000Z',
          updated_at: '2025-06-13T12:48:20.000Z',
          deleted_at: null,
          updated_by: 40900,
          created_by: 40900,
          min_temp: 2,
          max_temp: 8,
          min_temp_2: -25,
          max_temp_2: -15,
          min_temp_3: -90,
          max_temp_3: -60,
          is_coldstorage: 1,
          is_electricity: 1,
          description: null,
          is_selection: true,
        },
      },
      coldchain_capacity_equipment: null,
      latest_log: {
        temp: 13,
        updated_at: '2025-07-24T09:35:02.000Z',
        min_temp: null,
        max_temp: null,
      },
    },
  ] as TAssetInventoryChildData[],
}
